; MARKWORD initialization file
; Version 1.0.0.0.1
; Date and time: 2026-09-21 20:39:33 CEST
;
; The original MARKWORD.S does not read configuration values.
; Assign mMarkWord() and mLMarkWord() to unused keys in your TSE .ui file.
; Reserved for future settings.
