; MARKPAL configuration file
; Version: 1.0.0.0.1
; Date and time: 2026-09-21 17:37:31 CEST
;
; MARKPAL.S version 1.0.0.0.1 does not read configuration values from
; this file. Change the key definitions at the end of MARKPAL.S and
; recompile the macro when different keys are required.

[markpal]
version=1.0.0.0.1
