/*
    INTR32.S
    Version 1.0.0.0.2 - 2026-09-11
    Generated by OpenAI Codex (GPT-5)

    Windows replacement demonstration for the DOS INTR package.
*/

#INCLUDE ["intr32.inc"]

PROC PROCAddCurrentName()
    INTEGER indexI = 0
    INTEGER lengthI = 0
    STRING nameS[255] = ""

    lengthI = IntrGetNameLength()
    FOR indexI = 1 TO lengthI BY 1
        nameS = nameS + Chr(IntrGetNameChar(indexI))
    ENDFOR
    AddLine(nameS)
END

PROC PROCBuildDirectory()
    INTEGER foundB = FALSE
    INTEGER closedB = FALSE
    INTEGER countI = 0

    foundB = IntrFindFirst()
    WHILE foundB
        PROCAddCurrentName()
        countI = countI + 1
        foundB = IntrFindNext()
    ENDWHILE
    closedB = IntrCloseFind()
    IF countI
        Warn("INTR32 1.0.0.0.2: ", countI,
             " directory names inserted. OpenAI Codex (GPT-5).")
    ELSE
        Warn("INTR32 1.0.0.0.2: No directory names were found. OpenAI Codex (GPT-5).")
    ENDIF
END

PROC PROCSetLargeCursor()
    IF IntrSetConsoleCursor(100, TRUE)
        Warn("INTR32 1.0.0.0.2: Console cursor changed to full size. OpenAI Codex (GPT-5).")
    ELSE
        Warn("INTR32 1.0.0.0.2: No Windows console cursor is available in this TSE window. OpenAI Codex (GPT-5).")
    ENDIF
END

<F1> PROCBuildDirectory()
<F2> PROCSetLargeCursor()
