// File: p214.s
// Purpose: Solve Project Euler problem 214
//          "Totient Chains"
//          Sum of all primes < 40,000,000 whose phi-chain length = 25
//
// Math:
//   phi(n) = Euler totient. Iterating phi generates a chain ending in 1.
//   E.g. 5->4->2->1 has length 4.
//   Find sum of all primes p < 40000000 where chain length = 25.
//
// Strategy:
//   1. Erase old pe214.py and pe214result.txt if present
//   2. Build Python solver line by line with AddLine()
//   3. Add Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe214.py, run via DOS(), read pe214result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Python: linear phi sieve + memoised chain lengths
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-27  Initial version by Claude (Anthropic)
//              Pattern from eulerproject0154.s (Claude/Anthropic)

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe214.py"
  String  resultFile[255]= "pe214result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If EditFile(pyFile)
    AbandonFile()
  EndIf
  EraseDiskFile(pyFile)
  PopPosition()
  PopBlock()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If EditFile(resultFile)
    AbandonFile()
  EndIf
  EraseDiskFile(resultFile)
  PopPosition()
  PopBlock()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // Line numbers are noted in comments; GotoLine() uses them
  // in the indentation block below.
  // No leading spaces in AddLine() -- added by InsertText().
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe214.py  --  generated by p214.s (TSE SAL)")               // line 1
  AddLine("# Project Euler 214 - Totient Chains")                        // line 2
  AddLine("# Sum primes < 40000000 with phi-chain length 25")            // line 3
  AddLine("LIMIT = 40000000")                                             // line 4
  AddLine("CHAIN = 25")                                                   // line 5
  AddLine("phi = list(range(LIMIT))")                                     // line 6
  AddLine("for p in range(2, LIMIT):")                                    // line 7
  AddLine("if phi[p] == p:")                                              // line 8   -> i1
  AddLine("for m in range(p, LIMIT, p):")                                 // line 9   -> i2
  AddLine("phi[m] = phi[m] // p * (p - 1)")                              // line 10  -> i2+i1
  AddLine("chain = [0] * LIMIT")                                          // line 11
  AddLine("chain[1] = 1")                                                 // line 12
  AddLine("for n in range(2, LIMIT):")                                    // line 13
  AddLine("stack = []")                                                   // line 14  -> i1
  AddLine("cur = n")                                                      // line 15  -> i1
  AddLine("while chain[cur] == 0:")                                       // line 16  -> i1
  AddLine("stack.append(cur)")                                            // line 17  -> i2
  AddLine("cur = phi[cur]")                                               // line 18  -> i2
  AddLine("length = chain[cur]")                                          // line 19  -> i1
  AddLine("for x in reversed(stack):")                                    // line 20  -> i1
  AddLine("length += 1")                                                  // line 21  -> i2
  AddLine("chain[x] = length")                                            // line 22  -> i2
  AddLine("total = sum(p for p in range(2, LIMIT) if phi[p] == p-1 and chain[p] == CHAIN)") // line 23
  AddLine("open('pe214result.txt','w').write(str(total))")                // line 24

  // -------------------------------------------------------
  // Insert Python indentation.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  GotoLine(8)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(9)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(10)  BegLine()  InsertText(i2)  InsertText(i1, _INSERT_)
  GotoLine(14)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(15)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(16)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i2, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result from file written by Python ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show answer in Warn box (take screenshot here) ---
  CopyToWinClip(answerStr)
  Warn("Project Euler 214 answer: ", answerStr)
  CopyToWinClip(answerStr)

  Return()
End
