/*
 Euler Project 212 - Combined Volume of Cuboids
 TSE SAL wrapper that creates and runs Python in the current directory

 <version>1.0.0.0.2</version>
 <history>
 1.0.0.0.2 - GPT-5.4 Thinking - Removed fragile InsertText indentation stage; Python lines are now written already indented.
 1.0.0.0.1 - GPT-5.4 Thinking - Fixed missing indentation variables in the initial Python-from-TSE version.
 1.0.0.0.0 - GPT-5.4 Thinking - Initial Python-from-TSE version for Project Euler 212.
 </history>

 Applied stored TSE SAL rules before publishing:
 - PROC Main() is the final procedure in the file.
 - RETURN() always uses parentheses.
 - No local/user variables named val or pos.
 - Only one final Warn() box is used.
 - CopyToWinClip() is called immediately before and immediately after the final Warn().
 - Final Warn() shows only the final result.
*/

PROC Main()
 INTEGER bufPyI = 0
 INTEGER bufResultI = 0
 STRING answerS[255] = ""
 STRING pyExeS[255] = "G:\LANGUAGE\COMPUTER\PYTHON\PYTHON\python.exe"
 STRING pyFileS[255] = "pe212.py"
 STRING resultFileS[255] = "pe212result.txt"
 STRING pyCmdS[255] = ""

 PushLocation()
 PushBlock()

 IF EditFile( pyFileS )
  AbandonFile()
 ENDIF
 EraseDiskFile( pyFileS )

 IF EditFile( resultFileS )
  AbandonFile()
 ENDIF
 EraseDiskFile( resultFileS )

 bufPyI = CreateTempBuffer()
 GotoBufferId( bufPyI )
 BegFile()

 AddLine( "# pe212.py -- generated by eulerproject0212.s (TSE SAL)" )
 AddLine( "# Project Euler 212 - Combined Volume of Cuboids" )
 AddLine( "# Expected answer: 328968937309" )
 AddLine( "" )
 AddLine( "def union_area(rects):" )
 AddLine( "    if not rects:" )
 AddLine( "        return 0" )
 AddLine( "    zvals = []" )
 AddLine( "    events = []" )
 AddLine( "    for y0, y1, z0, z1 in rects:" )
 AddLine( "        if y0 >= y1 or z0 >= z1:" )
 AddLine( "            continue" )
 AddLine( "        zvals.append(z0)" )
 AddLine( "        zvals.append(z1)" )
 AddLine( "        events.append((y0, 1, z0, z1))" )
 AddLine( "        events.append((y1, -1, z0, z1))" )
 AddLine( "    if not events:" )
 AddLine( "        return 0" )
 AddLine( "    zvals = sorted(set(zvals))" )
 AddLine( "    if len(zvals) <= 1:" )
 AddLine( "        return 0" )
 AddLine( "    zindex = {}" )
 AddLine( "    for idx, value in enumerate(zvals):" )
 AddLine( "        zindex[value] = idx" )
 AddLine( "    events2 = []" )
 AddLine( "    for y, typ, z0, z1 in events:" )
 AddLine( "        events2.append((y, typ, zindex[z0], zindex[z1]))" )
 AddLine( "    events2.sort()" )
 AddLine( "    m = len(zvals) - 1" )
 AddLine( "    count = [0] * (m * 4 + 20)" )
 AddLine( "    length = [0] * (m * 4 + 20)" )
 AddLine( "    def update(node, left, right, ql, qr, delta):" )
 AddLine( "        if ql >= right or qr <= left:" )
 AddLine( "            return" )
 AddLine( "        if ql <= left and right <= qr:" )
 AddLine( "            count[node] += delta" )
 AddLine( "        else:" )
 AddLine( "            mid = (left + right) // 2" )
 AddLine( "            update(node * 2, left, mid, ql, qr, delta)" )
 AddLine( "            update(node * 2 + 1, mid, right, ql, qr, delta)" )
 AddLine( "        if count[node] > 0:" )
 AddLine( "            length[node] = zvals[right] - zvals[left]" )
 AddLine( "        elif right - left == 1:" )
 AddLine( "            length[node] = 0" )
 AddLine( "        else:" )
 AddLine( "            length[node] = length[node * 2] + length[node * 2 + 1]" )
 AddLine( "    area = 0" )
 AddLine( "    prev_y = events2[0][0]" )
 AddLine( "    for y, typ, zi0, zi1 in events2:" )
 AddLine( "        dy = y - prev_y" )
 AddLine( "        if dy:" )
 AddLine( "            area += dy * length[1]" )
 AddLine( "        update(1, 0, m, zi0, zi1, typ)" )
 AddLine( "        prev_y = y" )
 AddLine( "    return area" )
 AddLine( "" )
 AddLine( "def solve():" )
 AddLine( "    n = 50000" )
 AddLine( "    total_count = 6 * n" )
 AddLine( "    s = [0] * (total_count + 1)" )
 AddLine( "    for k in range(1, 56):" )
 AddLine( "        s[k] = (100003 - 200003 * k + 300007 * k * k * k) % 1000000" )
 AddLine( "    for k in range(56, total_count + 1):" )
 AddLine( "        s[k] = (s[k - 24] + s[k - 55]) % 1000000" )
 AddLine( "    cuboids = []" )
 AddLine( "    max_x = 0" )
 AddLine( "    for c in range(n):" )
 AddLine( "        x0 = s[6 * c + 1] % 10000" )
 AddLine( "        y0 = s[6 * c + 2] % 10000" )
 AddLine( "        z0 = s[6 * c + 3] % 10000" )
 AddLine( "        dx = 1 + (s[6 * c + 4] % 399)" )
 AddLine( "        dy = 1 + (s[6 * c + 5] % 399)" )
 AddLine( "        dz = 1 + (s[6 * c + 6] % 399)" )
 AddLine( "        x1 = x0 + dx" )
 AddLine( "        y1 = y0 + dy" )
 AddLine( "        z1 = z0 + dz" )
 AddLine( "        cuboids.append((x0, x1, y0, y1, z0, z1))" )
 AddLine( "        if x1 > max_x:" )
 AddLine( "            max_x = x1" )
 AddLine( "    starts = [[] for dummy in range(max_x + 1)]" )
 AddLine( "    ends = [[] for dummy in range(max_x + 1)]" )
 AddLine( "    for x0, x1, y0, y1, z0, z1 in cuboids:" )
 AddLine( "        rect = (y0, y1, z0, z1)" )
 AddLine( "        starts[x0].append(rect)" )
 AddLine( "        ends[x1].append(rect)" )
 AddLine( "    active = {}" )
 AddLine( "    volume = 0" )
 AddLine( "    for x in range(max_x):" )
 AddLine( "        for rect in starts[x]:" )
 AddLine( "            active[rect] = active.get(rect, 0) + 1" )
 AddLine( "        for rect in ends[x]:" )
 AddLine( "            current_count = active.get(rect, 0)" )
 AddLine( "            if current_count <= 1:" )
 AddLine( "                if rect in active:" )
 AddLine( "                    del active[rect]" )
 AddLine( "            else:" )
 AddLine( "                active[rect] = current_count - 1" )
 AddLine( "        if active:" )
 AddLine( "            volume += union_area(list(active.keys()))" )
 AddLine( "    return volume" )
 AddLine( "" )
 AddLine( "answer = solve()" )
 AddLine( "with open('pe212result.txt', 'w') as handle:" )
 AddLine( "    handle.write(str(answer))" )

 SaveAs( pyFileS, _OVERWRITE_ )
 AbandonFile()

 pyCmdS = QuotePath( pyExeS ) + " " + QuotePath( pyFileS )
 DOS( pyCmdS, _DONT_PROMPT_ )

 bufResultI = CreateTempBuffer()
 GotoBufferId( bufResultI )
 InsertFile( resultFileS )
 BegFile()
 answerS = Trim( GetText( 1, CurrLineLen() ) )
 AbandonFile()

 CopyToWinClip( answerS )
 Warn( answerS )
 CopyToWinClip( answerS )

 PopBlock()
 PopLocation()
 RETURN()
END
