// ============================================================
// File: eulerproject0259.s
// Purpose: Create and run a Python program for Project Euler 259
//          "Reachable Numbers"
//
// <version>19</version>
// LLM: ChatGPT GPT-5.4 Thinking
//
// History:
//   19 - ChatGPT - Creates pe259.py from TSE SAL, runs it,
//                  reads pe259result.txt, shows/copies result.
// ============================================================

PROC Main()
  INTEGER bufferPyI = 0
  INTEGER bufferResultI = 0
  STRING answerS[255] = ""
  STRING pythonExeS[255] = "g:\language\computer\python\python\python.exe"
  STRING pythonFileS[255] = "pe259.py"
  STRING resultFileS[255] = "pe259result.txt"
  STRING commandS[255] = ""
  STRING quoteS[2] = ""
  //
  quoteS = Chr( 34 )
  //
  PushLocation()
  PushBlock()
  IF EditFile( pythonFileS )
    AbandonFile()
  ENDIF
  EraseDiskFile( pythonFileS )
  PopBlock()
  PopLocation()
  //
  PushLocation()
  PushBlock()
  IF EditFile( resultFileS )
    AbandonFile()
  ENDIF
  EraseDiskFile( resultFileS )
  PopBlock()
  PopLocation()
  //
  bufferPyI = CreateTempBuffer()
  GotoBufferId( bufferPyI )
  BegFile()
  //
  AddLine( "# pe259.py -- generated by eulerproject0259.s (TSE SAL)" )
  AddLine( "# Project Euler 259 - Reachable Numbers" )
  AddLine( "" )
  AddLine( "class Fraction:" )
  AddLine( "    def __init__(self, numerator, denominator=1):" )
  AddLine( "        self.numerator = int(numerator)" )
  AddLine( "        self.denominator = int(denominator)" )
  AddLine( "" )
  AddLine( "    def __add__(self, other):" )
  AddLine( "        return Fraction(" )
  AddLine( "            self.numerator * other.denominator + other.numerator * self.denominator," )
  AddLine( "            self.denominator * other.denominator," )
  AddLine( "        )" )
  AddLine( "" )
  AddLine( "    def __mul__(self, other):" )
  AddLine( "        return Fraction(" )
  AddLine( "            self.numerator * other.numerator," )
  AddLine( "            self.denominator * other.denominator," )
  AddLine( "        )" )
  AddLine( "" )
  AddLine( "    def __truediv__(self, other):" )
  AddLine( "        return Fraction(" )
  AddLine( "            self.numerator * other.denominator," )
  AddLine( "            self.denominator * other.numerator," )
  AddLine( "        )" )
  AddLine( "" )
  AddLine( "    def __lt__(self, other):" )
  AddLine( "        return self.numerator * other.denominator < other.numerator * self.denominator" )
  AddLine( "" )
  AddLine( "    def __eq__(self, other):" )
  AddLine( "        return self.numerator * other.denominator == other.numerator * self.denominator" )
  AddLine( "" )
  AddLine( "" )
  AddLine( "def search(digits):" )
  AddLine( "    result = [Fraction(int(digits))]" )
  AddLine( "" )
  AddLine( "    for split in range(1, len(digits)):" )
  AddLine( "        left = digits[:split]" )
  AddLine( "        right = digits[split:]" )
  AddLine( "" )
  AddLine( "        left_fractions = search(left)" )
  AddLine( "        right_fractions = search(right)" )
  AddLine( "" )
  AddLine( "        for x in left_fractions:" )
  AddLine( "            for y in right_fractions:" )
  AddLine( "                result.append(x + y)" )
  AddLine( "                result.append(x + Fraction(-y.numerator, y.denominator))" )
  AddLine( "                result.append(x * y)" )
  AddLine( "                if y.numerator != 0:" )
  AddLine( "                    result.append(x / y)" )
  AddLine( "" )
  AddLine( "    if len(result) > 1:" )
  AddLine( "        result.sort()" )
  AddLine( "        unique = [result[0]]" )
  AddLine( "        for current in result[1:]:" )
  AddLine( "            if not (current == unique[-1]):" )
  AddLine( "                unique.append(current)" )
  AddLine( "        result = unique" )
  AddLine( "" )
  AddLine( "    return result" )
  AddLine( "" )
  AddLine( "" )
  AddLine( "def solve(last_digit):" )
  AddLine( "    digits = '123456789'[:last_digit]" )
  AddLine( "" )
  AddLine( "    fractions = search(digits)" )
  AddLine( "" )
  AddLine( "    found = []" )
  AddLine( "    for current in fractions:" )
  AddLine( "        if current.denominator < 0:" )
  AddLine( "            current.numerator *= -1" )
  AddLine( "            current.denominator *= -1" )
  AddLine( "        if current.numerator <= 0:" )
  AddLine( "            continue" )
  AddLine( "        if current.numerator % current.denominator == 0:" )
  AddLine( "            found.append(current.numerator // current.denominator)" )
  AddLine( "" )
  AddLine( "    found.sort()" )
  AddLine( "    unique = []" )
  AddLine( "    for value in found:" )
  AddLine( "        if not unique or value != unique[-1]:" )
  AddLine( "            unique.append(value)" )
  AddLine( "" )
  AddLine( "    total = 0" )
  AddLine( "    for value in unique:" )
  AddLine( "        total += value" )
  AddLine( "" )
  AddLine( "    return total" )
  AddLine( "" )
  AddLine( "" )
  AddLine( "def main():" )
  AddLine( "    answer = str(solve(9))" )
  AddLine( "    open('pe259result.txt', 'w').write(answer)" )
  AddLine( "" )
  AddLine( "" )
  AddLine( "if __name__ == '__main__':" )
  AddLine( "    main()" )
  //
  SaveAs( pythonFileS, _OVERWRITE_ )
  AbandonFile( bufferPyI )
  //
  commandS = quoteS + pythonExeS + quoteS + " " + quoteS + pythonFileS + quoteS
  Dos( commandS, _DONT_PROMPT_ )
  //
  bufferResultI = CreateTempBuffer()
  GotoBufferId( bufferResultI )
  InsertFile( resultFileS )
  BegFile()
  answerS = GetText( 1, CurrLineLen() )
  AbandonFile( bufferResultI )
  //
  CopyToWinClip( answerS )
  Warn( answerS )
  CopyToWinClip( answerS )
END
