/*
Euler Project 216
The Primality of 2n^2 - 1

version 1.0.0.0.1
history:
- 1.0.0.0.1  Created by ChatGPT GPT-5.4 Thinking

Notes:
- This TSE SAL program creates a Python program, runs it, then reads back the result.
- Final answer is copied to clipboard before and after the final Warn() box.
- Python program also performs the Project Euler sample check for n <= 10000 => 2202.
*/

Proc Main()
 Integer bufPyI        = 0
 Integer bufResultI    = 0
 String  answerS[255]  = ""
 String  pyExeS[255]   = "g:\language\computer\python\python\python.exe"
 String  pyFileS[255]  = "pe216.py"
 String  resultFileS[255] = "pe216result.txt"
 String  pyCmdS[255]   = ""
 String  indent1S[8]   = "    "
 String  indent2S[16]  = "        "
 String  indent3S[24]  = "            "

 // --- Erase old Python script file ---
 PushLocation()
 If EditFile( pyFileS )
  AbandonFile()
 EndIf
 EraseDiskFile( pyFileS )
 PopLocation()

 // --- Erase old result file ---
 PushLocation()
 If EditFile( resultFileS )
  AbandonFile()
 EndIf
 EraseDiskFile( resultFileS )
 PopLocation()

 // -------------------------------------------------------
 // Build the Python script line by line.
 // No leading spaces in AddLine() -- added below by InsertText().
 // -------------------------------------------------------
 bufPyI = CreateTempBuffer()
 GotoBufferId( bufPyI )
 BegFile()

 AddLine( "# pe216.py -- generated by eulerproject0216.s (TSE SAL)" )                    // 1
 AddLine( "import math" )                                                                 // 2
 AddLine( "" )                                                                            // 3
 AddLine( "N = 50000000" )                                                                // 4
 AddLine( "SAMPLE_N = 10000" )                                                            // 5
 AddLine( "RESULT_FILE = 'pe216result.txt'" )                                             // 6
 AddLine( "" )                                                                            // 7
 AddLine( "def mul_mod(a, b, m):" )                                                       // 8
 AddLine( "return (a * b) % m" )                                                          // 9 -> i1
 AddLine( "" )                                                                            // 10
 AddLine( "def pow_mod(a, e, m):" )                                                       // 11
 AddLine( "return pow(a, e, m)" )                                                         // 12 -> i1
 AddLine( "" )                                                                            // 13
 AddLine( "def tonelli_shanks(n, p):" )                                                   // 14
 AddLine( "if n == 0:" )                                                                  // 15 -> i1
 AddLine( "return 0" )                                                                    // 16 -> i2
 AddLine( "if p == 2:" )                                                                  // 17 -> i1
 AddLine( "return n" )                                                                    // 18 -> i2
 AddLine( "if pow(n, (p - 1) // 2, p) != 1:" )                                            // 19 -> i1
 AddLine( "return -1" )                                                                   // 20 -> i2
 AddLine( "if p % 4 == 3:" )                                                              // 21 -> i1
 AddLine( "return pow(n, (p + 1) // 4, p)" )                                              // 22 -> i2
 AddLine( "q = p - 1" )                                                                   // 23 -> i1
 AddLine( "s = 0" )                                                                       // 24 -> i1
 AddLine( "while (q & 1) == 0:" )                                                         // 25 -> i1
 AddLine( "q >>= 1" )                                                                     // 26 -> i2
 AddLine( "s += 1" )                                                                      // 27 -> i2
 AddLine( "z = 2" )                                                                       // 28 -> i1
 AddLine( "while pow(z, (p - 1) // 2, p) != p - 1:" )                                     // 29 -> i1
 AddLine( "z += 1" )                                                                      // 30 -> i2
 AddLine( "m = s" )                                                                       // 31 -> i1
 AddLine( "c = pow(z, q, p)" )                                                            // 32 -> i1
 AddLine( "t = pow(n, q, p)" )                                                            // 33 -> i1
 AddLine( "r = pow(n, (q + 1) // 2, p)" )                                                 // 34 -> i1
 AddLine( "while t != 1:" )                                                               // 35 -> i1
 AddLine( "i = 1" )                                                                       // 36 -> i2
 AddLine( "tt = (t * t) % p" )                                                            // 37 -> i2
 AddLine( "while tt != 1:" )                                                              // 38 -> i2
 AddLine( "tt = (tt * tt) % p" )                                                          // 39 -> i3
 AddLine( "i += 1" )                                                                      // 40 -> i3
 AddLine( "b = c" )                                                                       // 41 -> i2
 AddLine( "for _ in range(m - i - 1):" )                                                  // 42 -> i2
 AddLine( "b = (b * b) % p" )                                                             // 43 -> i3
 AddLine( "r = (r * b) % p" )                                                             // 44 -> i2
 AddLine( "c = (b * b) % p" )                                                             // 45 -> i2
 AddLine( "t = (t * c) % p" )                                                             // 46 -> i2
 AddLine( "m = i" )                                                                       // 47 -> i2
 AddLine( "return r" )                                                                    // 48 -> i1
 AddLine( "" )                                                                            // 49
 AddLine( "def prime_sieve(limit):" )                                                     // 50
 AddLine( "if limit < 2:" )                                                               // 51 -> i1
 AddLine( "return []" )                                                                   // 52 -> i2
 AddLine( "size = (limit // 2) + 1" )                                                     // 53 -> i1
 AddLine( "flags = bytearray(b'\x01') * size" )                                           // 54 -> i1
 AddLine( "flags[0] = 0" )                                                                // 55 -> i1
 AddLine( "root = int(math.isqrt(limit))" )                                               // 56 -> i1
 AddLine( "p = 3" )                                                                       // 57 -> i1
 AddLine( "while p <= root:" )                                                            // 58 -> i1
 AddLine( "if flags[p // 2]:" )                                                           // 59 -> i2
 AddLine( "step = p" )                                                                    // 60 -> i3
 AddLine( "start = (p * p) // 2" )                                                        // 61 -> i3
 AddLine( "flags[start::step] = b'\x00' * (((size - 1 - start) // step) + 1)" )          // 62 -> i3
 AddLine( "p += 2" )                                                                      // 63 -> i2
 AddLine( "primes = [2]" )                                                                // 64 -> i1
 AddLine( "primes.extend(2 * i + 1 for i in range(1, size) if flags[i])" )               // 65 -> i1
 AddLine( "return primes" )                                                               // 66 -> i1
 AddLine( "" )                                                                            // 67
 AddLine( "def count_t_primes(limit_n):" )                                                // 68
 AddLine( "alive = bytearray(b'\x01') * (limit_n + 1)" )                                  // 69 -> i1
 AddLine( "alive[0] = 0" )                                                                // 70 -> i1
 AddLine( "alive[1] = 0" )                                                                // 71 -> i1
 AddLine( "max_t = 2 * limit_n * limit_n - 1" )                                           // 72 -> i1
 AddLine( "prime_limit = int(math.isqrt(max_t))" )                                        // 73 -> i1
 AddLine( "primes = prime_sieve(prime_limit)" )                                           // 74 -> i1
 AddLine( "for p in primes:" )                                                            // 75 -> i1
 AddLine( "if p == 2:" )                                                                  // 76 -> i2
 AddLine( "continue" )                                                                    // 77 -> i3
 AddLine( "r8 = p & 7" )                                                                  // 78 -> i2
 AddLine( "if not (r8 == 1 or r8 == 7):" )                                                // 79 -> i2
 AddLine( "continue" )                                                                    // 80 -> i3
 AddLine( "inv2 = (p + 1) // 2" )                                                         // 81 -> i2
 AddLine( "root = tonelli_shanks(inv2, p)" )                                              // 82 -> i2
 AddLine( "if root <= 0:" )                                                               // 83 -> i2
 AddLine( "continue" )                                                                    // 84 -> i3
 AddLine( "root2 = p - root" )                                                            // 85 -> i2
 AddLine( "first = root" )                                                                // 86 -> i2
 AddLine( "while first <= limit_n:" )                                                     // 87 -> i2
 AddLine( "t = 2 * first * first - 1" )                                                   // 88 -> i3
 AddLine( "if t != p:" )                                                                  // 89 -> i3
 AddLine( "alive[first] = 0" )                                                            // 90 -> i4
 AddLine( "first += p" )                                                                  // 91 -> i3
 AddLine( "if root2 != root:" )                                                           // 92 -> i2
 AddLine( "second = root2" )                                                              // 93 -> i3
 AddLine( "while second <= limit_n:" )                                                    // 94 -> i3
 AddLine( "t = 2 * second * second - 1" )                                                 // 95 -> i4
 AddLine( "if t != p:" )                                                                  // 96 -> i4
 AddLine( "alive[second] = 0" )                                                           // 97 -> i5
 AddLine( "second += p" )                                                                 // 98 -> i4
 AddLine( "return sum(alive)" )                                                           // 99 -> i1
 AddLine( "" )                                                                            // 100
 AddLine( "sample = count_t_primes(SAMPLE_N)" )                                           // 101
 AddLine( "if sample != 2202:" )                                                          // 102
 AddLine( "open(RESULT_FILE, 'w').write('sample_failed_' + str(sample))" )                // 103 -> i1
 AddLine( "raise SystemExit" )                                                            // 104 -> i1
 AddLine( "answer = count_t_primes(N)" )                                                  // 105
 AddLine( "open(RESULT_FILE, 'w').write(str(answer))" )                                   // 106

 // -------------------------------------------------------
 // Insert Python indentation.
 // -------------------------------------------------------
 GotoBufferId( bufPyI )

 GotoLine(9)    BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(12)   BegLine()  InsertText( indent1S, _INSERT_ )

 GotoLine(15)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(16)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(17)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(18)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(19)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(20)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(21)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(22)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(23)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(24)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(25)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(26)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(27)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(28)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(29)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(30)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(31)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(32)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(33)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(34)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(35)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(36)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(37)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(38)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(39)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(40)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(41)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(42)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(43)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(44)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(45)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(46)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(47)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(48)   BegLine()  InsertText( indent1S, _INSERT_ )

 GotoLine(51)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(52)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(53)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(54)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(55)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(56)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(57)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(58)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(59)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(60)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(61)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(62)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(63)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(64)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(65)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(66)   BegLine()  InsertText( indent1S, _INSERT_ )

 GotoLine(69)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(70)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(71)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(72)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(73)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(74)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(75)   BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(76)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(77)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(78)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(79)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(80)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(81)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(82)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(83)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(84)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(85)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(86)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(87)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(88)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(89)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(90)   BegLine()  InsertText( indent3S + indent1S, _INSERT_ )
 GotoLine(91)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(92)   BegLine()  InsertText( indent2S, _INSERT_ )
 GotoLine(93)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(94)   BegLine()  InsertText( indent3S, _INSERT_ )
 GotoLine(95)   BegLine()  InsertText( indent3S + indent1S, _INSERT_ )
 GotoLine(96)   BegLine()  InsertText( indent3S + indent1S, _INSERT_ )
 GotoLine(97)   BegLine()  InsertText( indent3S + indent2S, _INSERT_ )
 GotoLine(98)   BegLine()  InsertText( indent3S + indent1S, _INSERT_ )
 GotoLine(99)   BegLine()  InsertText( indent1S, _INSERT_ )

 GotoLine(103)  BegLine()  InsertText( indent1S, _INSERT_ )
 GotoLine(104)  BegLine()  InsertText( indent1S, _INSERT_ )

 // --- Save Python script to disk ---
 SaveAs( pyFileS, _OVERWRITE_ )
 AbandonFile( bufPyI )

 // --- Run Python ---
 pyCmdS = pyExeS + " " + pyFileS
 DOS( pyCmdS, _DONT_PROMPT_ )

 // --- Read result file written by Python ---
 bufResultI = CreateTempBuffer()
 GotoBufferId( bufResultI )
 InsertFile( resultFileS )
 BegFile()
 answerS = GetText( 1, CurrLineLen() )
 AbandonFile( bufResultI )

 // --- Final answer only ---
 CopyToWinClip( answerS )
 Warn( answerS )
 CopyToWinClip( answerS )

 Return()
End
