// File: p154.s
// Purpose: Solve Project Euler problem 154
//          "Exploring Pascal's Pyramid"
//          How many coefficients in (x+y+z)^200000 are multiples of 10^12?
//
// Math:
//   Trinomial N!/(a!b!c!) with a+b+c=N=200000 is divisible by
//   10^12 = 2^12 * 5^12  iff (by Legendre's formula):
//     s2(a)+s2(b)+s2(c) >= 18  (base-2 digit sums; s2(200000)=6, need 6+12=18)
//     s5(a)+s5(b)+s5(c) >= 56  (base-5 digit sums; s5(200000)=8, need 8+48=56)
//   Iterate unordered triples a<=b<=c, a+b+c=N.
//   Symmetry: a==b or b==c -> count*3, else count*6.
//   Correct answer: 479742450
//
// Strategy:
//   1. Erase old pe154.py and pe154result.txt if present
//   2. Build numpy-based Python solver line by line with AddLine()
//   3. Add Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe154.py, run via DOS(), read pe154result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Python runtime: ~45-90 seconds (numpy vectorised inner loop)
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-21  Initial version by Claude (Anthropic)
//              Pattern from eulerproject0136.s (Perplexity/GPT-5.1)

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe154.py"
  String  resultFile[255]= "pe154result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If EditFile(pyFile)
    AbandonFile()
  EndIf
  EraseDiskFile(pyFile)
  PopPosition()
  PopBlock()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If EditFile(resultFile)
    AbandonFile()
  EndIf
  EraseDiskFile(resultFile)
  PopPosition()
  PopBlock()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // Line numbers are noted in comments; GotoLine() uses them
  // in the indentation block below.
  // No leading spaces in AddLine() -- added by InsertText().
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe154.py  --  generated by p154.s (TSE SAL)")           // line 1
  AddLine("# Project Euler 154 - Exploring Pascal's Pyramid")         // line 2
  AddLine("# Coefficients of (x+y+z)^200000 divisible by 10^12")     // line 3
  AddLine("import numpy as np")                                       // line 4
  AddLine("N     = 200000")                                           // line 5
  AddLine("S2MIN = 18")                                               // line 6
  AddLine("S5MIN = 56")                                               // line 7
  AddLine("s2 = np.array([bin(i).count('1') for i in range(N+1)], dtype=np.int8)") // line 8
  AddLine("s5 = np.zeros(N+1, dtype=np.int8)")                       // line 9
  AddLine("tmp = np.arange(N+1)")                                     // line 10
  AddLine("while np.any(tmp > 0):")                                   // line 11
  AddLine("s5 += (tmp % 5).astype(np.int8)")                         // line 12  -> i1
  AddLine("tmp //= 5")                                                // line 13  -> i1
  AddLine("count = 0")                                                // line 14
  AddLine("for a in range(0, N // 3 + 1):")                          // line 15
  AddLine("s5a = int(s5[a])")                                         // line 16  -> i1
  AddLine("s2a = int(s2[a])")                                         // line 17  -> i1
  AddLine("half = (N - a) // 2")                                      // line 18  -> i1
  AddLine("b = np.arange(a, half + 1, dtype=np.int32)")               // line 19  -> i1
  AddLine("c = (N - a) - b")                                          // line 20  -> i1
  AddLine("ok = ((s5a+s5[b]+s5[c]) >= S5MIN) & ((s2a+s2[b]+s2[c]) >= S2MIN)") // line 21  -> i1
  AddLine("bv = b[ok]")                                               // line 22  -> i1
  AddLine("cv = c[ok]")                                               // line 23  -> i1
  AddLine("eq = (bv == a) | (bv == cv)")                              // line 24  -> i1
  AddLine("count += int(np.sum(np.where(eq, 3, 6)))")                 // line 25  -> i1
  AddLine("open('pe154result.txt','w').write(str(count))")            // line 26

  // -------------------------------------------------------
  // Insert Python indentation.
  // GotoBufferId(bufPy) ensures we stay in the right buffer.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  GotoLine(12)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(13)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(16)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(23)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(24)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(25)  BegLine()  InsertText(i1, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done; ~45-90 seconds) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result from file written by Python ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show answer in Warn box (take screenshot here) ---
  Warn("Project Euler 154 answer: ", answerStr)

  // --- Copy only the bare number to clipboard ---
  CopyToWinClip(answerStr)

  Return()
End
