// File: p211.s
// Purpose: Solve Project Euler problem 211
//          "Divisor Square Sum"
//          Find the sum of all n, 0 < n < 64000000, such that
//          sigma2(n) = sum of squares of divisors of n is a perfect square.
//
// Strategy:
//   1. Erase old pe211.py and pe211result.txt if present
//   2. Build Python script line by line with AddLine()
//   3. Add Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe211.py, run via DOS(), read pe211result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Python algorithm (runtime ~60-90 seconds):
//   - Smallest Prime Factor (SPF) sieve via numpy int32  (~3s)
//   - Linear sigma2 sieve via sequential Python loop     (~55s)
//     sigma2[n] = sigma2[n/p^k] * sigma2(p^k)
//     sigma2(p^k) = (p^(2k+2)-1)/(p^2-1)
//   - Vectorised perfect-square check via numpy float64  (~4s)
//     sr = floor(sqrt(sigma2)); check sr^2 or (sr+1)^2 == sigma2
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-26  Initial version by Claude (Anthropic)
//              Pattern from eulerproject0154.s

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe211.py"
  String  resultFile[255]= "pe211result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If EditFile(pyFile)
    AbandonFile()
  EndIf
  EraseDiskFile(pyFile)
  PopPosition()
  PopBlock()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If EditFile(resultFile)
    AbandonFile()
  EndIf
  EraseDiskFile(resultFile)
  PopPosition()
  PopBlock()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // No leading spaces in AddLine() -- added via InsertText().
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe211.py  --  generated by p211.s (TSE SAL)")              // 1
  AddLine("# Project Euler 211 - Divisor Square Sum")                    // 2
  AddLine("# Sum of n < 64000000 where sigma2(n) is a perfect square")   // 3
  AddLine("import numpy as np, math")                                     // 4
  AddLine("N = 64000000")                                                 // 5
  AddLine("spf = np.arange(N+1, dtype=np.int32)")                        // 6
  AddLine("p = 2")                                                        // 7
  AddLine("while p*p <= N:")                                              // 8
  AddLine("if spf[p] == p:")                                              // 9   -> i1
  AddLine("spf[p*p::p] = np.where(")                                     // 10  -> i2
  AddLine("spf[p*p::p] == np.arange(p*p, N+1, p, dtype=np.int32),")     // 11  -> i2
  AddLine("p, spf[p*p::p])")                                              // 12  -> i2
  AddLine("p += 1")                                                       // 13  -> i1
  AddLine("sigma2 = np.zeros(N+1, dtype=np.uint64)")                     // 14
  AddLine("sigma2[1] = 1")                                                // 15
  AddLine("for n in range(2, N+1):")                                      // 16
  AddLine("p  = int(spf[n])")                                             // 17  -> i1
  AddLine("p2 = p*p")                                                     // 18  -> i1
  AddLine("n2 = n")                                                       // 19  -> i1
  AddLine("pk = 1")                                                       // 20  -> i1
  AddLine("while n2 % p == 0:")                                           // 21  -> i1
  AddLine("n2 //= p")                                                     // 22  -> i2
  AddLine("pk *= p")                                                      // 23  -> i2
  AddLine("s2pk     = (pk*pk*p2 - 1) // (p2 - 1)")                      // 24  -> i1
  AddLine("sigma2[n] = sigma2[n2] * s2pk")                               // 25  -> i1
  AddLine("sr   = np.floor(np.sqrt(sigma2.astype(np.float64))).astype(np.uint64)") // 26
  AddLine("mask = (sr*sr == sigma2) | ((sr+1)*(sr+1) == sigma2)")        // 27
  AddLine("idx  = np.arange(N+1, dtype=np.uint64)")                      // 28
  AddLine("ans  = int(np.sum(idx[mask]))")                                // 29
  AddLine("open('pe211result.txt','w').write(str(ans))")                  // 30

  // -------------------------------------------------------
  // Insert Python indentation.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  GotoLine( 9)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(10)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(11)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(12)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(13)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(23)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(24)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(25)  BegLine()  InsertText(i1, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done; ~60-90 seconds) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show and copy answer ---
  CopyToWinClip(answerStr)
  Warn("Project Euler 211 - Divisor Square Sum" + Chr(13) + "Answer: " + answerStr)
  CopyToWinClip(answerStr)

  Return()
End
