// Project Euler 249
// Prime subset sums
// <version>4</version>
// History: ChatGPT GPT-5.4 Thinking created this TSE SAL program
//
// Strategy:
//   1. Delete old pe249.py and pe249result.txt if present
//   2. Build exact Python solver line by line
//   3. Save pe249.py
//   4. Run Python from TSE
//   5. Read pe249result.txt
//   6. Copy bare answer to clipboard, show only bare answer in Warn(),
//      then copy bare answer again to clipboard
//
// The generated Python computes the answer exactly:
//   - primes below 5000
//   - subset-sum DP modulo 10^16
//   - sum counts for prime subset sums
//
// The final Warn() box shows only the final answer.

proc ProcDeleteFileIfExists( string fileNameS )
 PushLocation()
 IF EditFile( fileNameS )
  AbandonFile()
 ENDIF
 EraseDiskFile( fileNameS )
 PopLocation()
end

proc ProcIndentLine( integer bufferIdI, integer lineNumberI, string indentS )
 GotoBufferId( bufferIdI )
 GotoLine( lineNumberI )
 BegLine()
 InsertText( indentS, _INSERT_ )
end

PROC Main()
 integer bufferPyI = 0
 string answerS[255] = ""
 string pyExeS[255] = "G:\LANGUAGE\COMPUTER\PYTHON\PYTHON\python.exe"
 string pyFileS[255] = "pe249.py"
 string resultFileS[255] = "pe249result.txt"
 string pyCommandS[255] = ""
 string indent1S[255] = "    "

 ProcDeleteFileIfExists( pyFileS )
 ProcDeleteFileIfExists( resultFileS )

 bufferPyI = CreateTempBuffer()
 GotoBufferId( bufferPyI )
 BegFile()

 AddLine( "# pe249.py -- generated by eulerproject0249.s from TSE SAL" )                                        // 1
 AddLine( "# Project Euler 249 - Prime subset sums" )                                                           // 2
 AddLine( "MOD = 10 ** 16" )                                                                                    // 3
 AddLine( "LIMIT = 5000" )                                                                                      // 4
 AddLine( "flags = bytearray(b'\x01') * LIMIT" )                                                                // 5
 AddLine( "flags[0:2] = b'\x00\x00'" )                                                                          // 6
 AddLine( "root = int((LIMIT - 1) ** 0.5)" )                                                                    // 7
 AddLine( "for number in range(2, root + 1):" )                                                                 // 8
 AddLine( "if flags[number]:" )                                                                                 // 9
 AddLine( "start = number * number" )                                                                           // 10
 AddLine( "count = ((LIMIT - 1 - start) // number) + 1" )                                                       // 11
 AddLine( "flags[start:LIMIT:number] = b'\x00' * count" )                                                       // 12
 AddLine( "primes = [number for number in range(2, LIMIT) if flags[number]]" )                                 // 13
 AddLine( "maxsum = sum(primes)" )                                                                              // 14
 AddLine( "dp = [0] * (maxsum + 1)" )                                                                           // 15
 AddLine( "dp[0] = 1" )                                                                                         // 16
 AddLine( "reachable = 0" )                                                                                     // 17
 AddLine( "for prime in primes:" )                                                                              // 18
 AddLine( "for subtotal in range(reachable, -1, -1):" )                                                         // 19
 AddLine( "ways = dp[subtotal]" )                                                                               // 20
 AddLine( "if ways:" )                                                                                          // 21
 AddLine( "dp[subtotal + prime] = (dp[subtotal + prime] + ways) % MOD" )                                        // 22
 AddLine( "reachable += prime" )                                                                                // 23
 AddLine( "primeflags = bytearray(b'\x01') * (maxsum + 1)" )                                                    // 24
 AddLine( "primeflags[0:2] = b'\x00\x00'" )                                                                     // 25
 AddLine( "root2 = int(maxsum ** 0.5)" )                                                                        // 26
 AddLine( "for number in range(2, root2 + 1):" )                                                                // 27
 AddLine( "if primeflags[number]:" )                                                                            // 28
 AddLine( "start = number * number" )                                                                           // 29
 AddLine( "count = ((maxsum - start) // number) + 1" )                                                          // 30
 AddLine( "primeflags[start:maxsum + 1:number] = b'\x00' * count" )                                             // 31
 AddLine( "answer = 0" )                                                                                        // 32
 AddLine( "for number in range(2, maxsum + 1):" )                                                               // 33
 AddLine( "if primeflags[number]:" )                                                                            // 34
 AddLine( "answer = (answer + dp[number]) % MOD" )                                                              // 35
 AddLine( "open('pe249result.txt', 'w').write(str(answer).zfill(16))" )                                         // 36

 ProcIndentLine( bufferPyI, 9,  indent1S )
 ProcIndentLine( bufferPyI, 10, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 11, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 12, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 19, indent1S )
 ProcIndentLine( bufferPyI, 20, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 21, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 22, indent1S + indent1S + indent1S )
 ProcIndentLine( bufferPyI, 23, indent1S )
 ProcIndentLine( bufferPyI, 28, indent1S )
 ProcIndentLine( bufferPyI, 29, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 30, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 31, indent1S + indent1S )
 ProcIndentLine( bufferPyI, 34, indent1S )
 ProcIndentLine( bufferPyI, 35, indent1S + indent1S )

 SaveAs( pyFileS, _OVERWRITE_ )
 AbandonFile( bufferPyI )

 pyCommandS = QuotePath( pyExeS ) + " " + QuotePath( pyFileS )
 DOS( pyCommandS, _DONT_PROMPT_ )

 PushLocation()
 IF EditFile( resultFileS )
  BegFile()
  answerS = GetText( 1, CurrLineLen() )
  CopyToWinClip( answerS )
  Warn( answerS )
  CopyToWinClip( answerS )
  AbandonFile()
 ELSE
  answerS = "NO_RESULT_FILE"
  CopyToWinClip( answerS )
  Warn( answerS )
  CopyToWinClip( answerS )
 ENDIF
 PopLocation()

 Return()
END
