// Euler Project 248
// <version>5</version>
// History:
// 5 - GPT-5.4 Thinking - TSE SAL program that generates and runs a Python solver for Euler Project 248.

PROC Main()
  INTEGER bufPyI = 0
  INTEGER bufResultI = 0
  STRING answerS[255] = ""
  STRING pyExeS[255] = "g:\language\computer\python\python\python.exe"
  STRING pyFileS[255] = "pe248.py"
  STRING resultFileS[255] = "pe248result.txt"
  STRING pyCmdS[255] = ""
  STRING i1S[4] = "    "
  STRING i2S[8] = "        "
  STRING i3S[12] = "            "
  STRING i4S[16] = "                "
  STRING i5S[20] = "                    "
  STRING i6S[24] = "                        "
  STRING i7S[28] = "                            "
  STRING i8S[32] = "                                "
  //
  PushLocation()
  IF EditFile( pyFileS )
    AbandonFile()
  ENDIF
  EraseDiskFile( pyFileS )
  PopLocation()
  //
  PushLocation()
  IF EditFile( resultFileS )
    AbandonFile()
  ENDIF
  EraseDiskFile( resultFileS )
  PopLocation()
  //
  bufPyI = CreateTempBuffer()
  GotoBufferId( bufPyI )
  BegFile()
  //
  AddLine( "# pe248.py -- generated by eulerproject0248.s" )
  AddLine( "# Project Euler 248" )
  AddLine( "# Find the 150000th n with phi(n) = 13!" )
  AddLine( "from math import isqrt" )
  AddLine( "TARGET = (10, 5, 2, 1, 1, 1)" )
  AddLine( "SMALL = (2, 3, 5, 7, 11, 13)" )
  AddLine( "TARGET_INDEX = 149999" )
  AddLine( "LIMIT = 6227020800" )
  AddLine( "def sieve(limit):" )
  AddLine( "    flags = [True] * (limit + 1)" )
  AddLine( "    flags[0] = False" )
  AddLine( "    flags[1] = False" )
  AddLine( "    p = 2" )
  AddLine( "    while p * p <= limit:" )
  AddLine( "        if flags[p]:" )
  AddLine( "            step = p" )
  AddLine( "            start = p * p" )
  AddLine( "            flags[start:limit + 1:step] = [False] * (((limit - start) // step) + 1)" )
  AddLine( "        p += 1" )
  AddLine( "    return [i for i, ok in enumerate(flags) if ok]" )
  AddLine( "PRIMES = sieve(isqrt(LIMIT) + 1)" )
  AddLine( "def is_prime(n):" )
  AddLine( "    if n < 2:" )
  AddLine( "        return False" )
  AddLine( "    for p in PRIMES:" )
  AddLine( "        if p * p > n:" )
  AddLine( "            return True" )
  AddLine( "        if n % p == 0:" )
  AddLine( "            return n == p" )
  AddLine( "    return True" )
  AddLine( "divs = [1]" )
  AddLine( "for p, e in zip(SMALL, TARGET):" )
  AddLine( "    new_divs = []" )
  AddLine( "    mul = 1" )
  AddLine( "    for _ in range(e + 1):" )
  AddLine( "        for d in divs:" )
  AddLine( "            new_divs.append(d * mul)" )
  AddLine( "        mul *= p" )
  AddLine( "    divs = new_divs" )
  AddLine( "cands = []" )
  AddLine( "for d in divs:" )
  AddLine( "    p = d + 1" )
  AddLine( "    if is_prime(p):" )
  AddLine( "        exps = [0, 0, 0, 0, 0, 0]" )
  AddLine( "        t = d" )
  AddLine( "        for i, q in enumerate(SMALL):" )
  AddLine( "            while t % q == 0:" )
  AddLine( "                exps[i] += 1" )
  AddLine( "                t //= q" )
  AddLine( "        bump = -1" )
  AddLine( "        if p == 2:" )
  AddLine( "            bump = 0" )
  AddLine( "        elif p == 3:" )
  AddLine( "            bump = 1" )
  AddLine( "        elif p == 5:" )
  AddLine( "            bump = 2" )
  AddLine( "        elif p == 7:" )
  AddLine( "            bump = 3" )
  AddLine( "        elif p == 11:" )
  AddLine( "            bump = 4" )
  AddLine( "        elif p == 13:" )
  AddLine( "            bump = 5" )
  AddLine( "        cands.append((p, tuple(exps), bump))" )
  AddLine( "cands.sort()" )
  AddLine( "answers = []" )
  AddLine( "def dfs(start, r2, r3, r5, r7, r11, r13, current):" )
  AddLine( "    if r2 == 0 and r3 == 0 and r5 == 0 and r7 == 0 and r11 == 0 and r13 == 0:" )
  AddLine( "        answers.append(current)" )
  AddLine( "        return" )
  AddLine( "    for idx in range(start, len(cands)):" )
  AddLine( "        p, base, bump = cands[idx]" )
  AddLine( "        a2, a3, a5, a7, a11, a13 = base" )
  AddLine( "        if a2 > r2 or a3 > r3 or a5 > r5 or a7 > r7 or a11 > r11 or a13 > r13:" )
  AddLine( "            continue" )
  AddLine( "        factor = p" )
  AddLine( "        b2, b3, b5, b7, b11, b13 = a2, a3, a5, a7, a11, a13" )
  AddLine( "        while b2 <= r2 and b3 <= r3 and b5 <= r5 and b7 <= r7 and b11 <= r11 and b13 <= r13:" )
  AddLine( "            dfs(idx + 1, r2 - b2, r3 - b3, r5 - b5, r7 - b7, r11 - b11, r13 - b13, current * factor)" )
  AddLine( "            if bump < 0:" )
  AddLine( "                break" )
  AddLine( "            factor *= p" )
  AddLine( "            if bump == 0:" )
  AddLine( "                b2 += 1" )
  AddLine( "            elif bump == 1:" )
  AddLine( "                b3 += 1" )
  AddLine( "            elif bump == 2:" )
  AddLine( "                b5 += 1" )
  AddLine( "            elif bump == 3:" )
  AddLine( "                b7 += 1" )
  AddLine( "            elif bump == 4:" )
  AddLine( "                b11 += 1" )
  AddLine( "            else:" )
  AddLine( "                b13 += 1" )
  AddLine( "dfs(0, 10, 5, 2, 1, 1, 1, 1)" )
  AddLine( "answers.sort()" )
  AddLine( "with open('pe248result.txt', 'w') as f:" )
  AddLine( "    f.write(str(answers[TARGET_INDEX]))" )
  //
  SaveAs( pyFileS, _OVERWRITE_ )
  AbandonFile()
  //
  pyCmdS = pyExeS + " " + pyFileS
  DOS( pyCmdS, _DONT_PROMPT_ )
  //
  bufResultI = CreateTempBuffer()
  InsertFile( resultFileS )
  BegFile()
  answerS = GetText( 1, CurrLineLen() )
  AbandonFile()
  //
  CopyToWinClip( answerS )
  Warn( answerS )
  CopyToWinClip( answerS )
  //
  RETURN()
END
