// File: p200.s
// Purpose: Solve Project Euler problem 200
//          "Prime-proof Squbes"
//          Find the 200th prime-proof sqube containing the substring "200".
//
// Math:
//   A sqube = p^2 * q^3 where p, q are distinct primes.
//   Prime-proof: no single digit replacement makes the number prime.
//   Generate all squbes up to a safe limit, keep those with "200",
//   sort, test each for prime-proof, count to 200.
//   Correct answer: 229161792008
//
// Strategy:
//   1. Erase old pe200.py and pe200result.txt if present
//   2. Build Python solver line by line with AddLine()
//   3. Add Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe200.py, run via DOS(), read pe200result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Python runtime: ~2-5 minutes (sympy isprime for trial division)
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-25  Initial version by Claude (Anthropic)
//              Pattern from eulerproject0154.s (Claude/Anthropic)

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe200.py"
  String  resultFile[255]= "pe200result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "
  String  i3[24]         = "            "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If EditFile(pyFile)
    AbandonFile()
  EndIf
  EraseDiskFile(pyFile)
  PopPosition()
  PopBlock()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If EditFile(resultFile)
    AbandonFile()
  EndIf
  EraseDiskFile(resultFile)
  PopPosition()
  PopBlock()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // No leading spaces in AddLine() -- added by InsertText().
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe200.py  --  generated by p200.s (TSE SAL)")              // 1
  AddLine("# Project Euler 200 - Prime-proof Squbes")                    // 2
  AddLine("# Find the 200th prime-proof sqube containing '200'")         // 3
  AddLine("from sympy import isprime, primerange")                       // 4
  AddLine("LIMIT  = 400_000_000_000")                                    // 5
  AddLine("TARGET = 200")                                                 // 6
  AddLine("primes_p = list(primerange(2, 223611))")                      // 7
  AddLine("primes_q = list(primerange(2, 4651))")                        // 8
  AddLine("squbes = set()")                                               // 9
  AddLine("for p in primes_p:")                                          // 10
  AddLine("p2 = p * p")                                                  // 11  -> i1
  AddLine("if p2 * 8 > LIMIT:")                                          // 12  -> i1
  AddLine("break")                                                        // 13  -> i2
  AddLine("for q in primes_q:")                                          // 14  -> i1
  AddLine("if q == p:")                                                   // 15  -> i2
  AddLine("continue")                                                     // 16  -> i3
  AddLine("sq = p2 * q * q * q")                                         // 17  -> i2
  AddLine("if sq > LIMIT:")                                               // 18  -> i2
  AddLine("break")                                                        // 19  -> i3
  AddLine("if '200' in str(sq):")                                         // 20  -> i2
  AddLine("squbes.add(sq)")                                               // 21  -> i3
  AddLine("squbes = sorted(squbes)")                                      // 22
  AddLine("def is_prime_proof(n):")                                       // 23
  AddLine("s = str(n)")                                                   // 24  -> i1
  AddLine("for i, ch in enumerate(s):")                                   // 25  -> i1
  AddLine("for d in '0123456789':")                                       // 26  -> i2
  AddLine("if d == ch:")                                                  // 27  -> i3
  AddLine("continue")                                                     // 28  -> i3+"    "
  AddLine("t = s[:i] + d + s[i+1:]")                                     // 29  -> i3
  AddLine("if t[0] == '0':")                                              // 30  -> i3
  AddLine("continue")                                                     // 31  -> i3+"    "
  AddLine("if isprime(int(t)):")                                          // 32  -> i3
  AddLine("return False")                                                 // 33  -> i3+"    "
  AddLine("return True")                                                  // 34  -> i1
  AddLine("count = 0")                                                    // 35
  AddLine("for sq in squbes:")                                            // 36
  AddLine("if is_prime_proof(sq):")                                       // 37  -> i1
  AddLine("count += 1")                                                   // 38  -> i2
  AddLine("if count == TARGET:")                                          // 39  -> i2
  AddLine("open('pe200result.txt','w').write(str(sq))")                   // 40  -> i3
  AddLine("break")                                                        // 41  -> i3

  // -------------------------------------------------------
  // Insert Python indentation.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  // for p loop body
  GotoLine(11)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(12)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(13)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(14)  BegLine()  InsertText(i1, _INSERT_)
  // for q loop body
  GotoLine(15)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(16)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i3, _INSERT_)
  // is_prime_proof body
  GotoLine(24)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(25)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(26)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(27)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(28)  BegLine()  InsertText(i3, _INSERT_)  InsertText(i1, _INSERT_)
  GotoLine(29)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(30)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(31)  BegLine()  InsertText(i3, _INSERT_)  InsertText(i1, _INSERT_)
  GotoLine(32)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(33)  BegLine()  InsertText(i3, _INSERT_)  InsertText(i1, _INSERT_)
  GotoLine(34)  BegLine()  InsertText(i1, _INSERT_)
  // main scan loop body
  GotoLine(37)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(38)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(39)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(40)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(41)  BegLine()  InsertText(i3, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show answer (take screenshot here) ---
  CopyToWinClip(answerStr)
  Warn("Project Euler P200 answer: ", answerStr)
  CopyToWinClip(answerStr)

  Return()
End
