// Euler Project 233
// TSE SAL program which creates and runs a Python solver
// <version>11</version>
// LLM: ChatGPT GPT-5.4 Thinking
// History:
// 1 - ChatGPT - Initial pure TSE SAL version for Euler 233
// 2 - ChatGPT - Faster redesign using direct exponent-pattern enumeration
// 3 - ChatGPT - Fixed TSE SAL rule: removed string #define, use local string variable instead
// 4 - ChatGPT - Faster redesign removing explicit third-prime loop via prefix classes
// 5 - ChatGPT - New version: generate and run Python solver from TSE SAL
// 6 - ChatGPT - Robust Python runner with exception result file and log fallback
// 7 - ChatGPT - Fixed clipboard copy by marking a block before CopyToWinClip()
// 8 - ChatGPT - Made clipboard helper use explicit PushBlock/PopBlock and exact temp buffer cleanup
// 9 - ChatGPT - Replaced failing TSE clipboard block copy with Windows clip.exe helper
// 10 - ChatGPT - Fixed Dos() command quoting by removing unnecessary quotes
// 11 - ChatGPT - Switched clipboard helper back to CopyToWinClip() temp-buffer method
//
// Rule check applied:
// - no own variables named val or pos
// - RETURN() always uses parentheses
// - one final Warn()
// - two clipboard copy calls around final Warn()
// - full program supplied
// - version number increased linearly
// - final Warn() shows only the final answer
//
FORWARD PROC ProcCopyAnswerToClipboard( STRING answerS )
//
PROC ProcCopyAnswerToClipboard( STRING answerS )
    INTEGER clipBufferIdI = 0
    STRING workS[255] = ""
    workS = answerS
    PushLocation()
    clipBufferIdI = CreateTempBuffer()
    GotoBufferId( clipBufferIdI )
    BegFile()
    AddLine( workS )
    BegFile()
    MarkAll()
    CopyToWinClip()
    AbandonFile()
    PopLocation()
END
//
PROC Main()
    INTEGER pyBufferIdI = 0
    STRING answerS[255] = ""
    STRING pyExeS[255] = "G:\LANGUAGE\COMPUTER\PYTHON\PYTHON\python.exe"
    STRING pyFileS[255] = "eulerproject0233.py"
    STRING resultFileS[255] = "eulerproject0233_result.txt"
    STRING logFileS[255] = "eulerproject0233_log.txt"
    STRING commandS[255] = ""
    //
    // Remove old Python script file if present.
    //
    PushLocation()
    IF EditFile( pyFileS )
        AbandonFile()
    ENDIF
    EraseDiskFile( pyFileS )
    PopLocation()
    //
    // Remove old result file if present.
    //
    PushLocation()
    IF EditFile( resultFileS )
        AbandonFile()
    ENDIF
    EraseDiskFile( resultFileS )
    PopLocation()
    //
    // Remove old log file if present.
    //
    PushLocation()
    IF EditFile( logFileS )
        AbandonFile()
    ENDIF
    EraseDiskFile( logFileS )
    PopLocation()
    //
    // Build the Python script in a temp buffer.
    //
    pyBufferIdI = CreateTempBuffer()
    GotoBufferId( pyBufferIdI )
    BegFile()
    AddLine( "# eulerproject0233.py -- generated by eulerproject0233.s" )
    AddLine( "from math import isqrt" )
    AddLine( "from array import array" )
    AddLine( "LIMIT = 100000000000" )
    AddLine( "MAX_X = LIMIT // (5 ** 3 * 13 ** 2)" )
    AddLine( "RESULT_FILE = 'eulerproject0233_result.txt'" )
    AddLine( "def solve():" )
    AddLine( "    spf = array('I', range(MAX_X + 1))" )
    AddLine( "    root = isqrt(MAX_X)" )
    AddLine( "    for prime in range(2, root + 1):" )
    AddLine( "        if spf[prime] == prime:" )
    AddLine( "            start = prime * prime" )
    AddLine( "            for multiple in range(start, MAX_X + 1, prime):" )
    AddLine( "                if spf[multiple] == multiple:" )
    AddLine( "                    spf[multiple] = prime" )
    AddLine( "    primes1 = [prime for prime in range(5, MAX_X + 1, 4) if spf[prime] == prime]" )
    AddLine( "    allowed = array('Q', [0])" )
    AddLine( "    oneExp1 = array('Q', [0])" )
    AddLine( "    oneExp3 = array('Q', [0])" )
    AddLine( "    for number in range(1, MAX_X + 1):" )
    AddLine( "        work = number" )
    AddLine( "        countOneMod4 = 0" )
    AddLine( "        exactExponent = 0" )
    AddLine( "        valid = True" )
    AddLine( "        while work > 1:" )
    AddLine( "            prime = spf[work]" )
    AddLine( "            exponent = 0" )
    AddLine( "            while (work % prime) == 0:" )
    AddLine( "                work //= prime" )
    AddLine( "                exponent += 1" )
    AddLine( "            if (prime % 4) == 1:" )
    AddLine( "                countOneMod4 += 1" )
    AddLine( "                exactExponent = exponent" )
    AddLine( "                if countOneMod4 > 1:" )
    AddLine( "                    valid = False" )
    AddLine( "                    break" )
    AddLine( "        allowedValue = allowed[-1]" )
    AddLine( "        oneExp1Value = oneExp1[-1]" )
    AddLine( "        oneExp3Value = oneExp3[-1]" )
    AddLine( "        if valid:" )
    AddLine( "            if countOneMod4 == 0:" )
    AddLine( "                allowedValue += number" )
    AddLine( "            elif countOneMod4 == 1:" )
    AddLine( "                if exactExponent == 1:" )
    AddLine( "                    oneExp1Value += number" )
    AddLine( "                elif exactExponent == 3:" )
    AddLine( "                    oneExp3Value += number" )
    AddLine( "        allowed.append(allowedValue)" )
    AddLine( "        oneExp1.append(oneExp1Value)" )
    AddLine( "        oneExp3.append(oneExp3Value)" )
    AddLine( "    total = 0" )
    AddLine( "    baseFixed = 5 ** 10" )
    AddLine( "    for qPrime in primes1:" )
    AddLine( "        if qPrime == 5:" )
    AddLine( "            continue" )
    AddLine( "        base = baseFixed * qPrime * qPrime" )
    AddLine( "        if base > LIMIT:" )
    AddLine( "            break" )
    AddLine( "        quotient = LIMIT // base" )
    AddLine( "        total += base * allowed[quotient]" )
    AddLine( "    for pPrime in primes1:" )
    AddLine( "        pPow7 = pPrime ** 7" )
    AddLine( "        if pPow7 > LIMIT:" )
    AddLine( "            break" )
    AddLine( "        quotient = LIMIT // pPow7" )
    AddLine( "        inner = oneExp3[quotient]" )
    AddLine( "        inner -= (pPrime ** 3) * allowed[quotient // (pPrime ** 3)]" )
    AddLine( "        total += pPow7 * inner" )
    AddLine( "    for pPrime in primes1:" )
    AddLine( "        pPow3 = pPrime ** 3" )
    AddLine( "        if pPow3 > LIMIT:" )
    AddLine( "            break" )
    AddLine( "        for qPrime in primes1:" )
    AddLine( "            if qPrime == pPrime:" )
    AddLine( "                continue" )
    AddLine( "            base = pPow3 * qPrime * qPrime" )
    AddLine( "            if base > LIMIT:" )
    AddLine( "                break" )
    AddLine( "            quotient = LIMIT // base" )
    AddLine( "            inner = oneExp1[quotient]" )
    AddLine( "            inner -= pPrime * allowed[quotient // pPrime]" )
    AddLine( "            inner -= qPrime * allowed[quotient // qPrime]" )
    AddLine( "            total += base * inner" )
    AddLine( "    return total" )
    AddLine( "try:" )
    AddLine( "    answer = str(solve())" )
    AddLine( "except Exception as exc:" )
    AddLine( "    answer = 'ERROR: ' + str(exc)" )
    AddLine( "handle = open(RESULT_FILE, 'w')" )
    AddLine( "handle.write(answer)" )
    AddLine( "handle.close()" )
    //
    // Save the generated Python file.
    //
    SaveAs( pyFileS, _OVERWRITE_ )
    PushLocation()
    GotoBufferId( pyBufferIdI )
    AbandonFile()
    PopLocation()
    //
    // Run Python and capture stdout/stderr in a log file.
    //
    commandS = "cmd /c " + pyExeS + " " + pyFileS + " > " + logFileS + " 2>&1"
    Dos( commandS, _DONT_PROMPT_ )
    //
    // Prefer the result file. If missing, fall back to the log file.
    //
    PushLocation()
    IF EditFile( resultFileS )
        BegFile()
        answerS = Trim( GetText( 1, CurrLineLen() ) )
        AbandonFile()
    ELSE
        IF EditFile( logFileS )
            BegFile()
            answerS = Trim( GetText( 1, CurrLineLen() ) )
            IF answerS == ""
                answerS = "ERROR: Python did not create result file"
            ENDIF
            AbandonFile()
        ELSE
            answerS = "ERROR: No result file and no log file"
        ENDIF
    ENDIF
    PopLocation()
    //
    // Final output.
    //
    ProcCopyAnswerToClipboard( answerS )
    Warn( answerS )
    ProcCopyAnswerToClipboard( answerS )
    RETURN()
END
