/*
  Euler Project 247
  TSE SAL program generating and running Python
  <version>6</version>

  History:
  - Created by ChatGPT GPT-5.4 Thinking
  - Pure TSE SAL wrapper generating pe247.py
  - Final answer copied before and after Warn()
*/

PROC Main()
  INTEGER bufPyI = 0
  INTEGER bufResultI = 0
  STRING answerS[255] = ""
  STRING pyExeS[255] = "G:\LANGUAGE\COMPUTER\PYTHON\PYTHON\python.exe"
  STRING pyFileS[255] = "pe247.py"
  STRING resultFileS[255] = "pe247result.txt"
  STRING pyCmdS[255] = ""

  PushLocation()
  PushBlock()
  IF EditFile( pyFileS )
    AbandonFile()
  ENDIF
  EraseDiskFile( pyFileS )
  PopBlock()
  PopLocation()

  PushLocation()
  PushBlock()
  IF EditFile( resultFileS )
    AbandonFile()
  ENDIF
  EraseDiskFile( resultFileS )
  PopBlock()
  PopLocation()

  bufPyI = CreateTempBuffer()
  GotoBufferId( bufPyI )
  BegFile()

  AddLine( "# pe247.py -- generated by TSE SAL" )
  AddLine( "import math" )
  AddLine( "import sys" )
  AddLine( "sys.setrecursionlimit(10000000)" )
  AddLine( "TARGET = 3" )
  AddLine( "best = None" )
  AddLine( "def side(x, y):" )
  AddLine( "    return (math.sqrt((x - y) * (x - y) + 4.0) - x - y) / 2.0" )
  AddLine( "def find_target(x, y, left, below):" )
  AddLine( "    global best" )
  AddLine( "    if left > TARGET or below > TARGET:" )
  AddLine( "        return" )
  AddLine( "    s = side(x, y)" )
  AddLine( "    if left == TARGET and below == TARGET:" )
  AddLine( "        if best is None or s < best:" )
  AddLine( "            best = s" )
  AddLine( "        return" )
  AddLine( "    find_target(x + s, y, left + 1, below)" )
  AddLine( "    find_target(x, y + s, left, below + 1)" )
  AddLine( "def count_above(x, y, limit):" )
  AddLine( "    s = side(x, y)" )
  AddLine( "    if s <= limit:" )
  AddLine( "        return 0" )
  AddLine( "    return 1 + count_above(x + s, y, limit) + count_above(x, y + s, limit)" )
  AddLine( "find_target(1.0, 0.0, 0, 0)" )
  AddLine( "answer = count_above(1.0, 0.0, best) + 1" )
  AddLine( "open('pe247result.txt', 'w').write(str(answer))" )

  SaveAs( pyFileS, _OVERWRITE_ )
  AbandonFile( bufPyI )

  pyCmdS = pyExeS + " " + pyFileS
  Dos( pyCmdS, _DONT_PROMPT_ )

  bufResultI = CreateTempBuffer()
  GotoBufferId( bufResultI )
  InsertFile( resultFileS )
  BegFile()
  answerS = GetText( 1, CurrLineLen() )
  AbandonFile( bufResultI )

  CopyToWinClip( answerS )
  Warn( answerS )
  CopyToWinClip( answerS )

  Return()
END
