// File: p213py.s
// Purpose: Solve Project Euler problem 213
//          "Flea Circus"
//          30x30 grid, 900 fleas (one per cell). After 50 bell rings each flea
//          jumps to a uniformly random adjacent cell. Find the expected number
//          of unoccupied squares, rounded to 6 decimal places.
//
// Strategy:
//   1. Erase old pe213.py and pe213result.txt if present
//   2. Build numpy-based Python solver line by line with AddLine()
//   3. Add Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe213.py, run via DOS(), read pe213result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Python runtime: ~1 second (numpy vectorised diffusion)
// Correct answer: 330.721154
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-26  Initial version
//              Pattern from eulerproject0154.s

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe213.py"
  String  resultFile[255]= "pe213result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "
  String  i3[16]         = "            "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If EditFile(pyFile)
    AbandonFile()
  EndIf
  EraseDiskFile(pyFile)
  PopPosition()
  PopBlock()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If EditFile(resultFile)
    AbandonFile()
  EndIf
  EraseDiskFile(resultFile)
  PopPosition()
  PopBlock()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // Indentation added below; no leading spaces in AddLine().
  // Line numbers for indentation block noted in comments.
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe213.py  --  generated by p213py.s (TSE SAL)")         // line  1
  AddLine("# Project Euler 213 - Flea Circus")                        // line  2
  AddLine("# Expected unoccupied squares on 30x30 grid after 50 rings") // line 3
  AddLine("import numpy as np")                                        // line  4
  AddLine("GRID = 30")                                                 // line  5
  AddLine("STEPS = 50")                                                // line  6
  AddLine("adj = np.zeros((GRID,GRID))")                               // line  7
  AddLine("adj[1:,:]  += 1")                                           // line  8
  AddLine("adj[:-1,:] += 1")                                           // line  9
  AddLine("adj[:,1:]  += 1")                                           // line 10
  AddLine("adj[:,:-1] += 1")                                           // line 11
  AddLine("log_emp = np.zeros(GRID*GRID)")                             // line 12
  AddLine("for sR in range(GRID):")                                    // line 13
  AddLine("for sC in range(GRID):")                                    // line 14  -> i1
  AddLine("cur = np.zeros((GRID,GRID))")                               // line 15  -> i2
  AddLine("cur[sR,sC] = 1.0")                                          // line 16  -> i2
  AddLine("for _ in range(STEPS):")                                    // line 17  -> i2
  AddLine("share = cur / adj")                                         // line 18  -> i3
  AddLine("nxt = np.zeros((GRID,GRID))")                               // line 19  -> i3
  AddLine("nxt[1:,:]  += share[:-1,:]")                               // line 20  -> i3
  AddLine("nxt[:-1,:] += share[1:,:]")                                // line 21  -> i3
  AddLine("nxt[:,1:]  += share[:,:-1]")                               // line 22  -> i3
  AddLine("nxt[:,:-1] += share[:,1:]")                                // line 23  -> i3
  AddLine("cur = nxt")                                                 // line 24  -> i3
  AddLine("p = cur.ravel()")                                           // line 25  -> i2
  AddLine("mask = p > 0")                                              // line 26  -> i2
  AddLine("log_emp[mask] += np.log1p(-p[mask])")                      // line 27  -> i2
  AddLine("total = float(np.sum(np.exp(log_emp)))")                   // line 28
  AddLine("open('pe213result.txt','w').write(f'{total:.6f}')")        // line 29

  // -------------------------------------------------------
  // Insert Python indentation.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  GotoLine(14)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(15)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(16)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(23)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(24)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(25)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(26)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(27)  BegLine()  InsertText(i2, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done; ~1 second) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result from file written by Python ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show answer in Warn box ---
  Warn("Project Euler 213 - Flea Circus", Chr(13),
       "Expected empty squares: ", answerStr)

  // --- Copy bare answer to clipboard ---
  CopyToWinClip(answerStr)

  Return()
End
