// Project Euler Problem 121 Solver
// Version: 2.0.0
// Author: Google Gemini
// History: Generated by Google Gemini (2026)

// Rules Confirmation:
// - No variables named 'val' or 'pos'.
// - Return() uses parentheses.
// - Warn() shows the final answer (2269).
// - CopyToWinClip() copies the answer only.
// - Used named Buffer variables: SetBufferInt(string, int, int).
// - Custom BigInt math (Base 1000) for 32-bit signed integer safety.
// - No floating point calculations.
// - % is undefined; MOD used instead.
// - AbandonFile() used instead of AbandonBuffer().
// - LLM Name: Google Gemini.

proc BigSetInt(integer value_to_set, string name, integer b_id)
    SetBufferInt(name, 1, b_id)
    SetBufferInt(name + "d1", value_to_set, b_id)
end

proc BigAdd(string nameA, string nameB, string nameRes, integer b_id)
    integer lenA = GetBufferInt(nameA, b_id)
    integer lenB = GetBufferInt(nameB, b_id)
    integer k, carry = 0, sum_val, max_l
    if lenA > lenB
        max_l = lenA
    else
        max_l = lenB
    endif
    for k = 1 to max_l
        sum_val = carry
        if k <= lenA
            sum_val = sum_val + GetBufferInt(nameA + "d" + Str(k), b_id)
        endif
        if k <= lenB
            sum_val = sum_val + GetBufferInt(nameB + "d" + Str(k), b_id)
        endif
        SetBufferInt(nameRes + "d" + Str(k), sum_val MOD 1000, b_id)
        carry = sum_val / 1000
    endfor
    if carry > 0
        max_l = max_l + 1
        SetBufferInt(nameRes + "d" + Str(max_l), carry, b_id)
    endif
    SetBufferInt(nameRes, max_l, b_id)
end

proc BigMulInt(string nameIn, integer factor, string nameRes, integer b_id)
    integer lenIn = GetBufferInt(nameIn, b_id)
    integer k, carry = 0, prod_val
    for k = 1 to lenIn
        prod_val = (GetBufferInt(nameIn + "d" + Str(k), b_id) * factor) + carry
        SetBufferInt(nameRes + "d" + Str(k), prod_val MOD 1000, b_id)
        carry = prod_val / 1000
    endfor
    while carry > 0
        lenIn = lenIn + 1
        SetBufferInt(nameRes + "d" + Str(lenIn), carry MOD 1000, b_id)
        carry = carry / 1000
    endwhile
    SetBufferInt(nameRes, lenIn, b_id)
end

proc BigCopy(string nameSrc, string nameDest, integer b_id)
    integer k, length_val = GetBufferInt(nameSrc, b_id)
    for k = 1 to length_val
        SetBufferInt(nameDest + "d" + Str(k), GetBufferInt(nameSrc + "d" + Str(k), b_id), b_id)
    endfor
    SetBufferInt(nameDest, length_val, b_id)
end

integer proc BigIsGte(string nameA, string nameB, integer b_id)
    integer lenA = GetBufferInt(nameA, b_id)
    integer lenB = GetBufferInt(nameB, b_id)
    integer k, vA, vB
    if lenA > lenB return(1) endif
    if lenA < lenB return(0) endif
    for k = lenA downto 1
        vA = GetBufferInt(nameA + "d" + Str(k), b_id)
        vB = GetBufferInt(nameB + "d" + Str(k), b_id)
        if vA > vB return(1) endif
        if vA < vB return(0) endif
    endfor
    return(1)
end

proc BigSub(string nameA, string nameB, integer b_id)
    integer lenA = GetBufferInt(nameA, b_id)
    integer lenB = GetBufferInt(nameB, b_id)
    integer k, borrow = 0, sub_val
    for k = 1 to lenA
        sub_val = GetBufferInt(nameA + "d" + Str(k), b_id) - borrow
        if k <= lenB
            sub_val = sub_val - GetBufferInt(nameB + "d" + Str(k), b_id)
        endif
        if sub_val < 0
            sub_val = sub_val + 1000
            borrow = 1
        else
            borrow = 0
        endif
        SetBufferInt(nameA + "d" + Str(k), sub_val, b_id)
    endfor
    while (lenA > 1) and (GetBufferInt(nameA + "d" + Str(lenA), b_id) == 0)
        lenA = lenA - 1
    endwhile
    SetBufferInt(nameA, lenA, b_id)
end

proc main()
    integer b_id = CreateTempBuffer()
    integer i, j, final_ans = 0
    string sI[2], sJ[2]

    for i = 0 to 15
        sI = Str(i)
        BigSetInt(0, "d" + sI, b_id)
        BigSetInt(0, "n" + sI, b_id)
    endfor

    BigSetInt(1, "d0", b_id)
    BigSetInt(1, "tot", b_id)

    for i = 1 to 15
        sI = Str(i)
        for j = 0 to 15
            BigSetInt(0, "n" + Str(j), b_id)
        endfor
        for j = 0 to i - 1
            sJ = Str(j)
            BigAdd("n" + Str(j + 1), "d" + sJ, "n" + Str(j + 1), b_id)
            BigMulInt("d" + sJ, i, "tmp", b_id)
            BigAdd("n" + sJ, "tmp", "n" + sJ, b_id)
        endfor
        for j = 0 to 15
            sJ = Str(j)
            BigCopy("n" + sJ, "d" + sJ, b_id)
        endfor
        BigMulInt("tot", i + 1, "tot", b_id)
    endfor

    BigSetInt(0, "win", b_id)
    for i = 8 to 15
        BigAdd("win", "d" + Str(i), "win", b_id)
    endfor

    while BigIsGte("tot", "win", b_id)
        BigSub("tot", "win", b_id)
        final_ans = final_ans + 1
    endwhile

    Warn(Str(final_ans))
    CopyToWinClip(Str(final_ans))

    AbandonFile(b_id)
    Return()
end
