// eulerproject0226.s
// <version>3.0.0.0.1</version>
// <history>
// 3.0.0.0.1 2026-03-31 Claude claude-sonnet-4-6
// - Rewritten: generates Python script and runs via DOS()
//   (pure SAL integer approach was unreliable due to shl/shr issues)
// - Python: rectangle rule, N=2000000 midpoint strips
//   blancmange B(x)=sum s(2^n*x)/2^n, 60 terms
//   integrand = B(x) - circle_bottom(x) where B(x) > cb(x)
//   result written to pe226result.txt
// - Answer: 0.11316017
// </history>
//
// Pattern from eulerproject0154.s (Python-via-DOS)
//
Proc Main()
  Integer bufPyI
  Integer bufResultI
  String  answerS[255]  = ""
  String  pyExeS[255]   = "g:\language\computer\python\python\python.exe"
  String  pyFileS[255]  = "pe226.py"
  String  resFileS[255] = "pe226result.txt"
  String  pyCmdS[255]   = ""
  String  i1S[8]        = "    "
  String  i2S[16]       = "        "

  // --- Erase old Python script ---
  PushPosition()
  PushBlock()
  If EditFile(pyFileS)
    AbandonFile()
  EndIf
  EraseDiskFile(pyFileS)
  PopPosition()
  PopBlock()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If EditFile(resFileS)
    AbandonFile()
  EndIf
  EraseDiskFile(resFileS)
  PopPosition()
  PopBlock()

  // -------------------------------------------------------
  // Build Python script line by line (no leading spaces).
  // Indentation added below via GotoLine/BegLine/InsertText.
  // -------------------------------------------------------
  bufPyI = CreateTempBuffer()
  GotoBufferId(bufPyI)
  BegFile()

  AddLine("# pe226.py -- generated by eulerproject0226.s (TSE SAL)")   // 1
  AddLine("# Project Euler 226: area under blancmange curve inside circle") // 2
  AddLine("# Circle C: centre (1/4,1/2), radius 1/4.")                 // 3
  AddLine("# Integrand = B(x)-cb(x) where B(x)>cb(x), x in circle.")  // 4
  AddLine("import numpy as np")                                         // 5
  AddLine("import math")                                                // 6
  AddLine("N = 2000000")                                               // 7
  AddLine("xs = np.linspace(1.0/(2*N), 1.0-1.0/(2*N), N)")            // 8
  AddLine("xs = xs[xs <= 0.5]")                                        // 9
  AddLine("disc = np.maximum(0.0, 1.0/16 - (xs-0.25)**2)")            // 10
  AddLine("mask = disc > 0")                                           // 11
  AddLine("sq   = np.where(mask, np.sqrt(np.maximum(0.0,disc)), 0.0)") // 12
  AddLine("cb   = 0.5 - sq")                                           // 13
  AddLine("bx = np.zeros(len(xs))")                                    // 14
  AddLine("t  = xs.copy()")                                            // 15
  AddLine("for n in range(60):")                                        // 16
  AddLine("tm = t % 1.0")                                              // 17  -> i1
  AddLine("d  = np.where(tm <= 0.5, tm, 1.0 - tm)")                   // 18  -> i1
  AddLine("bx += d / (2.0 ** n)")                                      // 19  -> i1
  AddLine("t  *= 2.0")                                                 // 20  -> i1
  AddLine("if np.max(d / (2.0 ** n)) < 1e-17:")                        // 21  -> i1
  AddLine("break")                                                      // 22  -> i2
  AddLine("vals = np.where(mask & (bx > cb), bx - cb, 0.0)")          // 23
  AddLine("result = np.sum(vals) / N")                                 // 24
  AddLine("s = '{:.8f}'.format(result)")                               // 25
  AddLine("open('pe226result.txt','w').write(s)")                      // 26

  // --- Add Python indentation ---
  GotoBufferId(bufPyI)

  GotoLine(17)  BegLine()  InsertText(i1S, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i1S, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i1S, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i1S, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i1S, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i2S, _INSERT_)

  // --- Save Python script ---
  SaveAs(pyFileS, _OVERWRITE_)
  AbandonFile(bufPyI)

  // --- Run Python ---
  pyCmdS = pyExeS + " " + pyFileS
  DOS(pyCmdS, _DEFAULT_ | _DEFAULT_ | _DONT_CLEAR_)

  // --- Read result ---
  bufResultI = CreateTempBuffer()
  InsertFile(resFileS)
  BegFile()
  answerS = GetText(1, CurrLineLen())
  AbandonFile(bufResultI)

  // --- Display and copy ---
  CopyToWinClip(answerS)
  Warn("PE226: area under blancmange curve inside circle" + Chr(13) + answerS)
  CopyToWinClip(answerS)
End
