/*  pe135_same_differences_buffer.s
 *
 *  Project Euler Problem 135 - Same differences
 *  Buffer-based array implementation (one line per n).
 *
 *  <version>1.0.0.0.1</version>
 *  Generated by: Perplexity (GPT-5.1)
 */

INTEGER bufferGI = 0
//

FORWARD INTEGER PROC GetCountI( INTEGER countsBufferI, INTEGER indexI )
FORWARD PROC SetCount( INTEGER countsBufferI, INTEGER indexI, INTEGER valueI )
FORWARD PROC IncCount( INTEGER countsBufferI, INTEGER indexI )
//

INTEGER PROC GetCountI( INTEGER countsBufferI, INTEGER indexI )
 INTEGER currBufferI = 0
 INTEGER currentLineI = 0
 STRING lineS[255] = ""
 INTEGER resultI = 0
 //
 currBufferI = GetBufferId()
 //
 PushPosition()
 GotoBufferId( countsBufferI )
 //
 currentLineI = indexI + 1
 //
 IF currentLineI <= NumLines()
  //
  GotoLine( currentLineI )
  BegLine()
  lineS = Trim( GetText( 1, 255 ) )
  //
 ELSE
  //
  lineS = "0"
  //
 ENDIF
 //
 resultI = Val( lineS )
 //
 GotoBufferId( currBufferI )
 PopPosition()
 //
 Return( resultI )
END
//

PROC SetCount( INTEGER countsBufferI, INTEGER indexI, INTEGER valueI )
 INTEGER currBufferI = 0
 INTEGER currentLineI = 0
 INTEGER linesI = 0
 STRING valueS[255] = ""
 //
 currBufferI = GetBufferId()
 //
 valueS = Str( valueI )
 //
 PushPosition()
 GotoBufferId( countsBufferI )
 //
 linesI = NumLines()
 currentLineI = indexI + 1
 //
 IF currentLineI <= linesI
  //
  GotoLine( currentLineI )
  BegLine()
  KillToEol()
  InsertText( valueS )
  //
 ELSE
  //
  GotoLine( linesI )
  //
  WHILE linesI < currentLineI - 1
   //
   AddLine( "0", countsBufferI )
   linesI = linesI + 1
   //
  ENDWHILE
  //
  AddLine( valueS, countsBufferI )
  //
 ENDIF
 //
 GotoBufferId( currBufferI )
 PopPosition()
 //
END
//

PROC IncCount( INTEGER countsBufferI, INTEGER indexI )
 INTEGER currentValueI = 0
 //
 currentValueI = GetCountI( countsBufferI, indexI )
 currentValueI = currentValueI + 1
 SetCount( countsBufferI, indexI, currentValueI )
 //
END
//

PROC Main()
 INTEGER limitI = 0
 INTEGER targetSolutionsI = 0
 INTEGER countsBufferI = 0
 INTEGER aI = 0
 INTEGER dI = 0
 INTEGER lowerDI = 0
 INTEGER upperDI = 0
 INTEGER nI = 0
 INTEGER idxI = 0
 INTEGER countI = 0
 INTEGER finalResultI = 0
 INTEGER orgBufferI = 0
 STRING resultS[255] = ""
 //
 limitI = 1000000
 targetSolutionsI = 10
 finalResultI = 0
 //
 orgBufferI = GetBufferId()
 //
 PushPosition() // 1
 bufferGI = CreateTempBuffer()
 PopPosition() // 1
 //
 PushPosition()
 countsBufferI = CreateTempBuffer()
 PopPosition()
 //
 aI = 1
 //
 WHILE aI < limitI
  //
  lowerDI = ( aI / 4 ) + 1
  upperDI = aI - 1
  //
  dI = lowerDI
  //
  WHILE dI <= upperDI
   //
   nI = aI * ( 4 * dI - aI )
   //
   IF nI >= limitI
    //
    BREAK
    //
   ENDIF
   //
   IncCount( countsBufferI, nI )
   //
   dI = dI + 1
   //
  ENDWHILE
  //
  aI = aI + 1
  //
 ENDWHILE
 //
 idxI = 0
 //
 WHILE idxI < limitI
  //
  countI = GetCountI( countsBufferI, idxI )
  //
  IF countI == targetSolutionsI
   //
   finalResultI = finalResultI + 1
   //
  ENDIF
  //
  idxI = idxI + 1
  //
 ENDWHILE
 //
 resultS = Str( finalResultI )
 //
 Warn( "Project Euler 135: count of n < 1,000,000 with exactly 10 solutions = ", resultS )
 AddLine( Format( "Project Euler 135: count of n < 1,000,000 with exactly 10 solutions = ", resultS ), bufferGI )
 //
 CopyToWinClip( resultS )
 //
 GotoBufferId( bufferGI )
 //
 AbandonFile( countsBufferI )
 GotoBufferId( orgBufferI )
 //
END

