// File: eulerproject0224.s
// Purpose: Solve Project Euler problem 224
//          "Almost Right-angled Triangles II"
//          Count integer-sided triangles a <= b <= c with
//          a^2 + b^2 = c^2 - 1  and  perimeter a+b+c <= 75,000,000.
//
// Math:
//   Rewrite c^2-b^2 = a^2+1  =>  (c-b)(c+b) = a^2+1.
//   Let d = c-b, e = c+b  =>  d*e = a^2+1, b=(e-d)/2, c=(e+d)/2.
//
//   Key observations:
//     1. All solutions have even a (odd a => no solutions, proven).
//     2. Even a => a^2+1 is odd => all divisors d are odd.
//
//   Algorithm: d-outer sieve with Tonelli-Shanks.
//     For each odd d from 1 to dMax (~10.36M):
//       Find ALL residues r where r^2 ð -1 (mod d):
//         - SPF sieve factors d in O(log d)
//         - Tonelli-Shanks solves r^2 ð -1 mod prime p in O(log^2 p)
//         - Hensel lifting raises solutions from mod p to mod p^e
//         - CRT combines solutions across prime power factors
//       For each residue r: step even a = r (or r+d), r+2d, r+4d, ...
//         checking bounds and counting valid triangles.
//   Total inner a-steps ~ 55 million. Runtime ~ 45-60 seconds.
//
// Strategy:
//   1. Erase old pe224.py and pe224result.txt if present
//   2. Build Python solver line by line with AddLine()
//   3. Add Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe224.py, run via DOS(), read pe224result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Expected answer : 4137330
// Python runtime  : ~45-60 seconds
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-28  Initial version by Claude (Anthropic)
//              Pattern from eulerproject0154.s

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe224.py"
  String  resultFile[255]= "pe224result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "
  String  i3[16]         = "            "
  String  i4[20]         = "                "
  String  i5[24]         = "                    "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If FileExists(pyFile)
    If EditFile(pyFile)
      AbandonFile()
    EndIf
  EndIf
  EraseDiskFile(pyFile)
  PopBlock()
  PopPosition()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If FileExists(resultFile)
    If EditFile(resultFile)
      AbandonFile()
    EndIf
  EndIf
  EraseDiskFile(resultFile)
  PopBlock()
  PopPosition()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // Indentation is inserted after all AddLine() calls.
  // No leading spaces here -- added by InsertText() below.
  // Line numbers are tracked in comments for the indent block.
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe224.py  --  generated by eulerproject0224.s (TSE SAL)")   //   1
  AddLine("# Project Euler 224: Almost Right-angled Triangles II")        //   2
  AddLine("# Count a<=b<=c: a^2+b^2=c^2-1, perimeter<=75000000")         //   3
  AddLine("import math")                                                   //   4
  AddLine("")                                                              //   5
  AddLine("LIMIT = 75000000")                                              //   6
  AddLine("")                                                              //   7
  AddLine("# --- Smallest prime factor sieve ---")                         //   8
  AddLine("dMax = int((LIMIT / 3.0) * 0.41422) + 2")                      //   9
  AddLine("spf = list(range(dMax + 1))")                                   //  10
  AddLine("i = 2")                                                         //  11
  AddLine("while i * i <= dMax:")                                          //  12
  AddLine("if spf[i] == i:")                                               //  13  i1
  AddLine("for j in range(i * i, dMax + 1, i):")                          //  14  i2
  AddLine("if spf[j] == j:")                                               //  15  i3
  AddLine("spf[j] = i")                                                    //  16  i4
  AddLine("i += 1")                                                        //  17  i1
  AddLine("")                                                              //  18
  AddLine("# --- Tonelli-Shanks: solve r^2 = -1 mod prime p ---")         //  19
  AddLine("def tonelli(p):")                                               //  20
  AddLine("n = p - 1")                                                     //  21  i1
  AddLine("if p == 2 or p % 4 == 3:")                                      //  22  i1
  AddLine("return []")                                                     //  23  i2
  AddLine("if pow(n, (p - 1) // 2, p) != 1:")                             //  24  i1
  AddLine("return []")                                                     //  25  i2
  AddLine("q, s = p - 1, 0")                                              //  26  i1
  AddLine("while q % 2 == 0:")                                            //  27  i1
  AddLine("q //= 2")                                                      //  28  i2
  AddLine("s += 1")                                                       //  29  i2
  AddLine("z = 2")                                                        //  30  i1
  AddLine("while pow(z, (p - 1) // 2, p) != p - 1:")                     //  31  i1
  AddLine("z += 1")                                                       //  32  i2
  AddLine("m, c, t, r = s, pow(z, q, p), pow(n, q, p), pow(n, (q + 1) // 2, p)")  //  33  i1
  AddLine("while True:")                                                  //  34  i1
  AddLine("if t == 1:")                                                   //  35  i2
  AddLine("break")                                                        //  36  i3
  AddLine("ii, tmp = 1, (t * t) % p")                                    //  37  i2
  AddLine("while tmp != 1:")                                              //  38  i2
  AddLine("tmp = (tmp * tmp) % p")                                       //  39  i3
  AddLine("ii += 1")                                                      //  40  i3
  AddLine("b = pow(c, 1 << (m - ii - 1), p)")                            //  41  i2
  AddLine("m, c, t, r = ii, (b*b)%p, (t*b*b)%p, (r*b)%p")              //  42  i2
  AddLine("if (r * r) % p != n % p:")                                    //  43  i1
  AddLine("return []")                                                    //  44  i2
  AddLine("return sorted(set([r, p - r]))")                              //  45  i1
  AddLine("")                                                             //  46
  AddLine("# --- Hensel lift: raise solution mod p to mod p^e ---")      //  47
  AddLine("def hensel(r, p, e):")                                        //  48
  AddLine("sols = [r, p - r] if r != p - r else [r]")                   //  49  i1
  AddLine("mod = p")                                                      //  50  i1
  AddLine("for _ in range(e - 1):")                                      //  51  i1
  AddLine("nmod = mod * p")                                               //  52  i2
  AddLine("ns = []")                                                      //  53  i2
  AddLine("for s in sols:")                                               //  54  i2
  AddLine("val = (s * s + 1) // mod")                                    //  55  i3
  AddLine("inv2s = pow(2 * s, p - 2, p)")                                //  56  i3
  AddLine("t = (-val * inv2s) % p")                                      //  57  i3
  AddLine("ns.append(s + t * mod)")                                      //  58  i3
  AddLine("sols = ns")                                                    //  59  i2
  AddLine("mod = nmod")                                                   //  60  i2
  AddLine("return sols")                                                  //  61  i1
  AddLine("")                                                             //  62
  AddLine("# --- CRT: combine two residue systems ---")                  //  63
  AddLine("def crt(r1, m1, r2, m2):")                                   //  64
  AddLine("return (r1 + m1 * ((r2 - r1) * pow(m1, -1, m2) % m2)) % (m1 * m2)")  //  65  i1
  AddLine("")                                                             //  66
  AddLine("# --- Residues mod d: all r with r^2 = -1 mod d ---")        //  67
  AddLine("def residues(d):")                                            //  68
  AddLine("if d == 1:")                                                  //  69  i1
  AddLine("return [0]")                                                  //  70  i2
  AddLine("factors = {}")                                                //  71  i1
  AddLine("n = d")                                                       //  72  i1
  AddLine("while n > 1:")                                                //  73  i1
  AddLine("p = spf[n]")                                                  //  74  i2
  AddLine("e = 0")                                                       //  75  i2
  AddLine("while n % p == 0:")                                           //  76  i2
  AddLine("n //= p")                                                     //  77  i3
  AddLine("e += 1")                                                      //  78  i3
  AddLine("factors[p] = e")                                              //  79  i2
  AddLine("for p in factors:")                                           //  80  i1
  AddLine("if p == 2 or p % 4 == 3:")                                   //  81  i2
  AddLine("return []")                                                   //  82  i3
  AddLine("pp_sols = []")                                                //  83  i1
  AddLine("for p, e in factors.items():")                                //  84  i1
  AddLine("rs = tonelli(p)")                                             //  85  i2
  AddLine("if not rs:")                                                  //  86  i2
  AddLine("return []")                                                   //  87  i3
  AddLine("lifted = []")                                                 //  88  i2
  AddLine("for rv in rs:")                                               //  89  i2
  AddLine("lifted.extend(hensel(rv, p, e))")                             //  90  i3
  AddLine("pp_sols.append((lifted, p ** e))")                            //  91  i2
  AddLine("res, mod = [0], 1")                                           //  92  i1
  AddLine("for sols, pp in pp_sols:")                                    //  93  i1
  AddLine("nr = []")                                                     //  94  i2
  AddLine("for rv in res:")                                              //  95  i2
  AddLine("for s in sols:")                                              //  96  i3
  AddLine("nr.append(crt(rv, mod, s, pp))")                             //  97  i4
  AddLine("res = nr")                                                    //  98  i2
  AddLine("mod *= pp")                                                   //  99  i2
  AddLine("return sorted(set(rv % d for rv in res))")                   // 100  i1
  AddLine("")                                                            // 101
  AddLine("# --- Main count ---")                                       // 102
  AddLine("count = 0")                                                  // 103
  AddLine("for d in range(1, dMax + 1, 2):")                           // 104
  AddLine("rlist = residues(d)")                                        // 105  i1
  AddLine("if not rlist:")                                              // 106  i1
  AddLine("continue")                                                   // 107  i2
  AddLine("for res in rlist:")                                          // 108  i1
  AddLine("if res % 2 == 0:")                                          // 109  i2
  AddLine("aStart = res if res >= 2 else res + 2 * d")                 // 110  i3
  AddLine("else:")                                                      // 111  i2
  AddLine("aStart = res + d")                                          // 112  i3
  AddLine("if aStart < 2:")                                             // 113  i3
  AddLine("aStart += 2 * d")                                           // 114  i4
  AddLine("if aStart == 0:")                                            // 115  i3
  AddLine("aStart = 2 * d")                                            // 116  i4
  AddLine("a = aStart")                                                 // 117  i2
  AddLine("while True:")                                                // 118  i2
  AddLine("N = a * a + 1")                                             // 119  i3
  AddLine("limE = LIMIT - a")                                          // 120  i3
  AddLine("if limE <= 0:")                                             // 121  i3
  AddLine("break")                                                     // 122  i4
  AddLine("dMin = (N + limE - 1) // limE")                            // 123  i3
  AddLine("if d < dMin:")                                              // 124  i3
  AddLine("break")                                                     // 125  i4
  AddLine("dMax_a = int(-a + math.sqrt(2.0 * a * a + 1.0))")         // 126  i3
  AddLine("if d <= dMax_a:")                                           // 127  i3
  AddLine("e = N // d")                                               // 128  i4
  AddLine("bv = (e - d) >> 1")                                        // 129  i4
  AddLine("if bv >= a and a + e <= LIMIT:")                           // 130  i4
  AddLine("count += 1")                                               // 131  i5
  AddLine("a += 2 * d")                                               // 132  i3
  AddLine("")                                                          // 133
  AddLine("with open('pe224result.txt', 'w') as f:")                  // 134
  AddLine("f.write(str(count))")                                      // 135  i1

  // -------------------------------------------------------
  // Insert Python indentation (GotoLine / BegLine / InsertText).
  // Each call prepends the indent string at the start of the line.
  // Multiple calls on the same line accumulate left-to-right.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  // SPF sieve body (lines 13-17)
  GotoLine(13)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(14)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(15)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(16)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i1, _INSERT_)

  // def tonelli body (lines 21-45)
  GotoLine(21)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(23)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(24)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(25)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(26)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(27)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(28)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(29)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(30)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(31)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(32)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(33)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(34)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(35)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(36)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(37)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(38)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(39)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(40)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(41)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(42)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(43)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(44)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(45)  BegLine()  InsertText(i1, _INSERT_)

  // def hensel body (lines 49-61)
  GotoLine(49)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(50)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(51)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(52)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(53)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(54)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(55)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(56)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(57)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(58)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(59)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(60)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(61)  BegLine()  InsertText(i1, _INSERT_)

  // def crt body (line 65)
  GotoLine(65)  BegLine()  InsertText(i1, _INSERT_)

  // def residues body (lines 69-100)
  GotoLine(69)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(70)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(71)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(72)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(73)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(74)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(75)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(76)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(77)   BegLine()  InsertText(i3, _INSERT_)
  GotoLine(78)   BegLine()  InsertText(i3, _INSERT_)
  GotoLine(79)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(80)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(81)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(82)   BegLine()  InsertText(i3, _INSERT_)
  GotoLine(83)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(84)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(85)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(86)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(87)   BegLine()  InsertText(i3, _INSERT_)
  GotoLine(88)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(89)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(90)   BegLine()  InsertText(i3, _INSERT_)
  GotoLine(91)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(92)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(93)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(94)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(95)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(96)   BegLine()  InsertText(i3, _INSERT_)
  GotoLine(97)   BegLine()  InsertText(i4, _INSERT_)
  GotoLine(98)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(99)   BegLine()  InsertText(i2, _INSERT_)
  GotoLine(100)  BegLine()  InsertText(i1, _INSERT_)

  // Main count loop (lines 105-132, 135)
  GotoLine(105)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(106)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(107)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(108)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(109)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(110)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(111)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(112)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(113)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(114)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(115)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(116)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(117)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(118)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(119)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(120)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(121)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(122)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(123)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(124)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(125)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(126)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(127)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(128)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(129)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(130)  BegLine()  InsertText(i4, _INSERT_)
  GotoLine(131)  BegLine()  InsertText(i5, _INSERT_)
  GotoLine(132)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(135)  BegLine()  InsertText(i1, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done; ~45-60 seconds) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result from file written by Python ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show answer (take screenshot here) ---
  CopyToWinClip(answerStr)
  Warn("Project Euler 224: Almost Right-angled Triangles II",
       Chr(13),
       "a^2 + b^2 = c^2 - 1,   perimeter <= 75,000,000",
       Chr(13), Chr(13),
       "Answer: ", answerStr)
  CopyToWinClip(answerStr)

  Return()
End
