// p029.s  -  Project Euler Problem 29: Distinct Powers
//
// How many distinct terms are in the sequence generated by a^b
// for 2 <= a <= 100 and 2 <= b <= 100?
//
// Strategy: SAL has no bignum type, so we cannot compute a^b directly for
// large values. Instead we represent each a^b by its prime-factorisation
// encoded as a canonical string "p1:e1,p2:e2,..." and count unique strings.
//
// Factorisation of a is computed once per base (a=2..100) and stored in a
// temp buffer (one per line, line k = factor(k+1), so line 1 = factor(2)).
// For each (a,b) we scale the exponents by b and look the key up in a second
// temp buffer.  New keys are added; the total line count is the answer.
//
// v1.0

// ---------------------------------------------------------------------------
// Global variables
// ---------------------------------------------------------------------------
integer gFactorBufId    // buffer: line k holds factorisation string for a=k+1
integer gKeyBufId       // buffer: one line per distinct a^b key seen so far

// ---------------------------------------------------------------------------
// BuildFactorStr
// Given integer n, return its prime factorisation as "p1:e1,p2:e2,..."
// e.g. 12 -> "2:2,3:1"
// ---------------------------------------------------------------------------
string proc BuildFactorStr(integer n)
    integer p
    integer e
    integer first
    string  s[255]
    string  part[40]
    s     = ""
    first = TRUE
    p     = 2
    while p * p <= n
        if n mod p == 0
            e = 0
            while n mod p == 0
                e = e + 1
                n = n / p
            endwhile
            part = Str(p) + ":" + Str(e)
            if first
                s     = part
                first = FALSE
            else
                s = s + "," + part
            endif
        endif
        p = p + 1
    endwhile
    if n > 1
        part = Str(n) + ":1"
        if first
            s = part
        else
            s = s + "," + part
        endif
    endif
    return( s )
end

// ---------------------------------------------------------------------------
// ScaleFactorStr
// Given factorisation string "p1:e1,p2:e2,..." multiply each exponent by b.
// This yields the canonical key for a^b.
// ---------------------------------------------------------------------------
string proc ScaleFactorStr(string fs, integer b)
    integer tokIdx
    integer colonPos
    integer eVal
    integer first
    string  token[80]
    string  pStr[20]
    string  eStr[20]
    string  result[255]
    result = ""
    first  = TRUE
    tokIdx = 1
    token  = GetToken(fs, ",", tokIdx)
    while Length(token) > 0
        colonPos = Pos(":", token)
        pStr     = SubStr(token, 1, colonPos - 1)
        eStr     = SubStr(token, colonPos + 1, Length(token) - colonPos)
        eVal     = Val(eStr) * b
        if first
            result = pStr + ":" + Str(eVal)
            first  = FALSE
        else
            result = result + "," + pStr + ":" + Str(eVal)
        endif
        tokIdx = tokIdx + 1
        token  = GetToken(fs, ",", tokIdx)
    endwhile
    return( result )
end

// ---------------------------------------------------------------------------
// KeySeen
// Returns TRUE if key already exists in gKeyBufId; otherwise adds it and
// returns FALSE.  Uses whole-line search so partial matches are excluded.
// ---------------------------------------------------------------------------
integer proc KeySeen(string key)
    integer savedId
    integer found
    savedId = GetBufferId()
    GotoBufferId( gKeyBufId )
    BegFile()
    found = lFind(key, "^g$")   // ^ = bol, g = global search, $ = eol
    if not found
        EndFile()
        AddLine( key )
    endif
    GotoBufferId( savedId )
    return( found )
end

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
proc Main()
    integer a
    integer b
    integer count
    string  fs[255]
    string  key[255]
    string  result[80]

    // -- create working buffers --
    gFactorBufId = CreateTempBuffer()
    gKeyBufId    = CreateTempBuffer()

    // -- precompute factorisation strings: line k = factor(k+1), k=1..99 --
    GotoBufferId( gFactorBufId )
    a = 2
    while a <= 100
        AddLine( BuildFactorStr(a) )
        a = a + 1
    endwhile

    // -- main double loop: count distinct a^b --
    count = 0
    a = 2
    while a <= 100
        // fetch precomputed factorisation for a  (stored at line a-1)
        GotoBufferId( gFactorBufId )
        GotoLine( a - 1 )
        fs = GetText(1, CurrLineLen())

        b = 2
        while b <= 100
            key = ScaleFactorStr(fs, b)
            if not KeySeen(key)
                count = count + 1
            endif
            b = b + 1
        endwhile

        a = a + 1
    endwhile

    // -- clean up --
    AbandonFile( gFactorBufId )
    AbandonFile( gKeyBufId )

    // -- report --
    result = "Project Euler #29 - Distinct Powers: " + Str(count)
    Warn( result )
    CopyToWinClip( result )
end
