// File: p192.s
// Purpose: Solve Project Euler problem 192
//          "Best Approximations"
//          Sum of denominators of best approximations to sqrt(n)
//          for n non-perfect-square, 1 < n <= 100000, bound D = 10^12.
//
// Strategy:
//   1. Erase old pe192.py and pe192result.txt if present
//   2. Build Python solver line by line with AddLine()
//   3. Insert Python indentation via GotoLine()+BegLine()+InsertText()
//   4. SaveAs pe192.py, run via DOS(), read pe192result.txt
//   5. Show result in Warn() box; copy bare answer to clipboard
//
// Correct answer: 57060635927998347
//
// <version>1.0.0.0.1</version>
// LLM: Claude claude-sonnet-4-6 (Anthropic)
//
// History:
//   1.0.0.0.1  2026-03-25  Initial version by Claude (Anthropic)
//              Pattern from eulerproject0154.s

Proc Main()
  Integer bufPy
  Integer bufResult
  String  answerStr[255] = ""
  String  pyExe[255]     = "g:\language\computer\python\python\python.exe"
  String  pyFile[255]    = "pe192.py"
  String  resultFile[255]= "pe192result.txt"
  String  pyCmd[255]     = ""
  String  i1[8]          = "    "
  String  i2[16]         = "        "
  String  i3[24]         = "            "

  // --- Erase old Python script file ---
  PushPosition()
  PushBlock()
  If FileExists(pyFile)
    If EditFile(pyFile)
      AbandonFile()
    EndIf
    EraseDiskFile(pyFile)
  EndIf
  PopBlock()
  PopPosition()

  // --- Erase old result file ---
  PushPosition()
  PushBlock()
  If FileExists(resultFile)
    If EditFile(resultFile)
      AbandonFile()
    EndIf
    EraseDiskFile(resultFile)
  EndIf
  PopBlock()
  PopPosition()

  // -------------------------------------------------------
  // Build the Python script line by line.
  // Indentation is inserted afterwards by GotoLine()+InsertText().
  // -------------------------------------------------------
  bufPy = CreateTempBuffer()
  GotoBufferId(bufPy)
  BegFile()

  AddLine("# pe192.py  --  generated by p192.s (TSE SAL)")
  AddLine("# Project Euler 192 - Best Approximations")
  AddLine("# Sum of best-approximation denominators, bound 10^12")
  AddLine("import math")
  AddLine("D = 10**12")
  AddLine("def best(n):")
  AddLine("a0 = math.isqrt(n)")
  AddLine("qp, qc = 0, 1")
  AddLine("pp, pc = 1, a0")
  AddLine("m, d, a = 0, 1, a0")
  AddLine("while True:")
  AddLine("m = a*d - m")
  AddLine("d = (n - m*m) // d")
  AddLine("a = (a0 + m) // d")
  AddLine("qn = a*qc + qp")
  AddLine("pn = a*pc + pp")
  AddLine("if qn > D:")
  AddLine("aN = a")
  AddLine("break")
  AddLine("qp, qc = qc, qn")
  AddLine("pp, pc = pc, pn")
  AddLine("t = (D - qp) // qc")
  AddLine("sq = t*qc + qp")
  AddLine("sp = t*pc + pp")
  AddLine("Ec = abs(pc*pc - n*qc*qc)")
  AddLine("Es = abs(sp*sp - n*sq*sq)")
  AddLine("if 2*t > aN:")
  AddLine("return sq")
  AddLine("elif 2*t < aN:")
  AddLine("return qc")
  AddLine("else:")
  AddLine("return qc if Ec*sq*sq < Es*qc*qc else sq")
  AddLine("total = 0")
  AddLine("for n in range(2, 100001):")
  AddLine("s = math.isqrt(n)")
  AddLine("if s*s != n:")
  AddLine("total += best(n)")
  AddLine("open('pe192result.txt','w').write(str(total))")

  // -------------------------------------------------------
  // Insert Python indentation.
  // -------------------------------------------------------
  GotoBufferId(bufPy)

  GotoLine(7)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(8)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(9)   BegLine()  InsertText(i1, _INSERT_)
  GotoLine(10)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(11)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(12)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(13)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(14)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(15)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(16)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(17)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(18)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(19)  BegLine()  InsertText(i3, _INSERT_)
  GotoLine(20)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(21)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(22)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(23)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(24)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(25)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(26)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(27)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(28)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(29)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(30)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(31)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(32)  BegLine()  InsertText(i2, _INSERT_)
  GotoLine(35)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(36)  BegLine()  InsertText(i1, _INSERT_)
  GotoLine(37)  BegLine()  InsertText(i2, _INSERT_)

  // --- Save Python script to disk ---
  SaveAs(pyFile, _OVERWRITE_)
  AbandonFile(bufPy)

  // --- Run Python (blocks until done) ---
  pyCmd = pyExe + " " + pyFile
  DOS(pyCmd, _DONT_PROMPT_)

  // --- Read result ---
  bufResult = CreateTempBuffer()
  InsertFile(resultFile)
  BegFile()
  answerStr = GetText(1, CurrLineLen())
  AbandonFile(bufResult)

  // --- Show and copy answer ---
  CopyToWinClip(answerStr)
  Warn("Project Euler 192 - Best Approximations", Chr(13),
       "Sum of best-approximation denominators for sqrt(n),", Chr(13),
       "n non-perfect-square, 1 < n <= 100000, bound 10^12:", Chr(13),
       Chr(13),
       answerStr)
  CopyToWinClip(answerStr)

  Return()
End
