// ===========================================================================
// euler70.s  --  TSE SAL solution for Project Euler Problem 70
// ---------------------------------------------------------------------------
// Problem (projecteuler.net/problem=70):
//   Find n, 1 < n < 10^7, for which phi(n) is a digit permutation of n
//   and  n / phi(n)  is minimised.
//
// Algorithm:
//   The answer is a semi-prime n = p*q (two distinct primes near sqrt(10^7)
//   ~ 3162), where phi(p*q) = (p-1)*(q-1).
//   Primes up to 10 000 are generated by trial division (no sieve array
//   needed) and stored one-per-line in a TSE temp buffer.
//
// TSE SAL constraints observed:
//   - No integer arrays (not supported).
//   - No reserved keywords used as variable names:
//     val, pos, left, right, str, length, chr, asc, upper, lower,
//     format, trim, substr are all reserved.
//   - Digit-frequency counting uses 10 individual integer variables.
//   - Overflow-safe ratio comparison uses three 2-digit fixed-point limbs
//     (all intermediates < 10^9, within 32-bit signed range).
//
// Expected answer:  n = 8319823  (= 2339 x 3557),  phi(n) = 8313928
// ===========================================================================

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------
constant SIEVE_LIMIT = 10000     // generate primes up to this value
constant LIMIT       = 10000000  // search n < 10^7

// ---------------------------------------------------------------------------
// Global buffer IDs  (no integer arrays used anywhere)
// ---------------------------------------------------------------------------
integer gPrimeBufId   // temp buffer: one prime per line
integer gPrimeCnt     // number of primes in gPrimeBufId

// ---------------------------------------------------------------------------
// integer proc GetPrime(integer nIdx)
//   Returns the nIdx-th prime (1-based) from gPrimeBufId.
//   Variable names avoid all TSE SAL reserved keywords.
// ---------------------------------------------------------------------------
integer proc GetPrime(integer nIdx)
    integer nSavedBuf
    integer nResult

    nSavedBuf = GetBufferId()
    GotoBufferId(gPrimeBufId)
    GotoLine(nIdx)
    nResult = Val(GetText(1, CurrLineLen()))
    GotoBufferId(nSavedBuf)
    return (nResult)
end

// ---------------------------------------------------------------------------
// proc BuildPrimes()
//   Generates all primes <= SIEVE_LIMIT by trial division and stores them
//   one per line in gPrimeBufId.  No integer arrays used.
// ---------------------------------------------------------------------------
proc BuildPrimes()
    integer nSavedBuf
    integer nCand, nFactor, nIsPrime, nIdx

    nSavedBuf   = GetBufferId()
    gPrimeBufId = CreateTempBuffer()
    gPrimeCnt   = 0

    // 2 is prime
    InsertLine("2")
    gPrimeCnt = 1

    // Test odd candidates from 3 upward
    nCand = 3
    while nCand <= SIEVE_LIMIT
        nIsPrime = TRUE

        nIdx = 1
        while nIdx <= gPrimeCnt
            nFactor = GetPrime(nIdx)
            if nFactor * nFactor > nCand
                nIdx = gPrimeCnt + 1          // break: no more factors possible
            elseif nCand mod nFactor == 0
                nIsPrime = FALSE
                nIdx     = gPrimeCnt + 1      // break: composite
            else
                nIdx = nIdx + 1
            endif
        endwhile

        if nIsPrime
            GotoBufferId(gPrimeBufId)
            EndFile()
            InsertLine(Str(nCand))
            gPrimeCnt = gPrimeCnt + 1
        endif

        nCand = nCand + 2
    endwhile

    GotoBufferId(nSavedBuf)
end

// ---------------------------------------------------------------------------
// integer proc IsPermutation(integer nA, integer nB)
//   Returns TRUE when nA and nB contain the same multiset of decimal digits.
//   Uses 10 individual integer variables (f0..f9) instead of an integer array.
//   Variable names avoid all TSE SAL reserved keywords.
// ---------------------------------------------------------------------------
integer proc IsPermutation(integer nA, integer nB)
    string  sA[12], sB[12]
    integer nLen, nPos2, nDigit
    integer f0, f1, f2, f3, f4, f5, f6, f7, f8, f9

    sA = Str(nA)
    sB = Str(nB)

    nLen = Length(sA)
    if nLen <> Length(sB)
        return (FALSE)
    endif

    f0 = 0   f1 = 0   f2 = 0   f3 = 0   f4 = 0
    f5 = 0   f6 = 0   f7 = 0   f8 = 0   f9 = 0

    // Count digits in nA
    nPos2 = 1
    while nPos2 <= nLen
        nDigit = Val(sA[nPos2:1])
        case nDigit
            when 0   f0 = f0 + 1
            when 1   f1 = f1 + 1
            when 2   f2 = f2 + 1
            when 3   f3 = f3 + 1
            when 4   f4 = f4 + 1
            when 5   f5 = f5 + 1
            when 6   f6 = f6 + 1
            when 7   f7 = f7 + 1
            when 8   f8 = f8 + 1
            when 9   f9 = f9 + 1
        endcase
        nPos2 = nPos2 + 1
    endwhile

    // Subtract digits in nB
    nPos2 = 1
    while nPos2 <= nLen
        nDigit = Val(sB[nPos2:1])
        case nDigit
            when 0   f0 = f0 - 1
            when 1   f1 = f1 - 1
            when 2   f2 = f2 - 1
            when 3   f3 = f3 - 1
            when 4   f4 = f4 - 1
            when 5   f5 = f5 - 1
            when 6   f6 = f6 - 1
            when 7   f7 = f7 - 1
            when 8   f8 = f8 - 1
            when 9   f9 = f9 - 1
        endcase
        nPos2 = nPos2 + 1
    endwhile

    // All counters must be zero for a permutation
    if f0 <> 0   return (FALSE)   endif
    if f1 <> 0   return (FALSE)   endif
    if f2 <> 0   return (FALSE)   endif
    if f3 <> 0   return (FALSE)   endif
    if f4 <> 0   return (FALSE)   endif
    if f5 <> 0   return (FALSE)   endif
    if f6 <> 0   return (FALSE)   endif
    if f7 <> 0   return (FALSE)   endif
    if f8 <> 0   return (FALSE)   endif
    if f9 <> 0   return (FALSE)   endif

    return (TRUE)
end

// ---------------------------------------------------------------------------
// integer proc RatioLess(integer nN, nPhi, nBh1, nBh2, nBh3)
//   Returns TRUE when nN/nPhi is strictly less than the ratio stored as
//   three 2-digit fixed-point limbs (nBh1, nBh2, nBh3).
//   All intermediate values are < 10^9, within 32-bit signed range.
// ---------------------------------------------------------------------------
integer proc RatioLess(integer nN,   integer nPhi,
                       integer nBh1, integer nBh2, integer nBh3)
    integer nV, nH1, nH2, nH3, nR1, nR2

    nV  = nN * 100
    nH1 = nV / nPhi
    if nH1 < nBh1   return (TRUE)   endif
    if nH1 > nBh1   return (FALSE)  endif

    nR1 = nV mod nPhi
    nV  = nR1 * 100
    nH2 = nV / nPhi
    if nH2 < nBh2   return (TRUE)   endif
    if nH2 > nBh2   return (FALSE)  endif

    nR2 = nV mod nPhi
    nV  = nR2 * 100
    nH3 = nV / nPhi
    return (nH3 < nBh3)
end

// ---------------------------------------------------------------------------
// proc Main()
// ---------------------------------------------------------------------------
proc Main()
    integer nI, nJ
    integer nP1, nP2
    integer nN, nPhi
    integer nBestN
    integer nBh1, nBh2, nBh3   // 2-digit limbs of best ratio
    integer nV, nR1, nR2        // scratch for limb update
    integer nDispPhi, nDispP1, nDispP2
    integer nSavedBuf, nResultBuf
    string  sAnswer[20]

    // ---- Step 1: Generate primes into a buffer ---------------------------
    BuildPrimes()

    // ---- Step 2: Initialise best ratio to sentinel 2.00 -----------------
    nBestN = 0
    nBh1   = 200   // 200/100 = 2.00
    nBh2   = 0
    nBh3   = 0

    // ---- Step 3: Enumerate semi-prime pairs nP1 <= nP2, nP1*nP2 < LIMIT -
    nI = 1
    while nI <= gPrimeCnt
        nP1 = GetPrime(nI)

        nJ = nI
        while nJ <= gPrimeCnt
            nP2 = GetPrime(nJ)
            nN  = nP1 * nP2

            if nN >= LIMIT
                nJ = gPrimeCnt + 1      // break inner loop
            else
                // phi(nP1 * nP2) = (nP1-1) * (nP2-1)  for distinct primes
                nPhi = (nP1 - 1) * (nP2 - 1)

                if IsPermutation(nN, nPhi)
                    if RatioLess(nN, nPhi, nBh1, nBh2, nBh3)
                        nBestN = nN

                        // Update stored best-ratio limbs
                        nV   = nN * 100
                        nBh1 = nV / nPhi
                        nR1  = nV mod nPhi
                        nV   = nR1 * 100
                        nBh2 = nV / nPhi
                        nR2  = nV mod nPhi
                        nV   = nR2 * 100
                        nBh3 = nV / nPhi
                    endif
                endif

                nJ = nJ + 1
            endif
        endwhile

        nI = nI + 1
    endwhile

    // ---- Step 4: Handle no-solution case ---------------------------------
    if nBestN == 0
        Warn("Euler 70: No solution found.")
        return ()
    endif

    // ---- Step 5: Recover prime factors and phi for display ---------------
    nDispPhi = 0
    nDispP1  = 0
    nDispP2  = 0
    nI = 1
    while nI <= gPrimeCnt
        nDispP1 = GetPrime(nI)
        if nDispP1 * nDispP1 > nBestN
            nI = gPrimeCnt + 1              // break
        elseif nBestN mod nDispP1 == 0
            nDispP2  = nBestN / nDispP1
            nDispPhi = (nDispP1 - 1) * (nDispP2 - 1)
            nI       = gPrimeCnt + 1        // break
        else
            nI = nI + 1
        endif
    endwhile

    // ---- Step 6: Copy answer to clipboard --------------------------------
    sAnswer = Str(nBestN)
    CopyToWinClip(sAnswer)

    // ---- Step 7: Write result to a new scratch buffer --------------------
    nSavedBuf  = GetBufferId()
    nResultBuf = CreateTempBuffer()
    GotoBufferId(nResultBuf)

    InsertLine("=================================================")
    InsertLine(" Project Euler  Problem 70 -- Totient Permutation")
    InsertLine("=================================================")
    InsertLine("")
    InsertLine(" Find n, 1 < n < 10^7, where phi(n) is a digit")
    InsertLine(" permutation of n and n / phi(n) is minimised.")
    InsertLine("")
    InsertLine("-------------------------------------------------")
    InsertLine("")
    InsertLine(" Answer:")
    InsertLine("")
    InsertLine("   n        = " + Str(nBestN))
    InsertLine("   phi(n)   = " + Str(nDispPhi))
    InsertLine("   Factors  = " + Str(nDispP1) + " x " + Str(nDispP2))
    InsertLine("   n/phi(n) ~ " +
               Str(nBh1 / 100) + "." +
               Format(nBh1 mod 100 : 2 : "0") +
               Format(nBh2         : 2 : "0") +
               Format(nBh3         : 2 : "0"))
    InsertLine("")
    InsertLine("   IsPermutation( n, phi(n) ) = TRUE")
    InsertLine("")
    InsertLine("-------------------------------------------------")
    InsertLine(" Primes generated up to : " + Str(SIEVE_LIMIT))
    InsertLine(" Semi-primes tested below: " + Str(LIMIT))
    InsertLine(" Total primes found      : " + Str(gPrimeCnt))
    InsertLine("=================================================")

    BegFile()

    Warn("Euler 70 done.  Answer: n = " + Str(nBestN) + "  (copied to clipboard)")
end

