/*
  Euler Project 193
  TSE SAL macro that creates and runs Python
  <version>1.0.0.0.1</version>

  LLM:
  GPT-5.4 Thinking (ChatGPT)

  History:
  2026-03-25  version 1.0.0.0.1
              Initial Python-from-TSE version.
              Pattern based on uploaded PE154 TSE/Python macro.

  Notes:
  - Creates pe193.py in the current working directory
  - Runs pe193.py with:
      g:\language\computer\python\python\python.exe
  - Reads result from pe193result.txt
  - Uses one final Warn() only
  - Copies only the bare final answer to clipboard
*/

PROC Main()
 integer bufPyI = 0
 integer bufResultI = 0
 string answerS[255] = ""
 string pyExeS[255] = "g:\language\computer\python\python\python.exe"
 string pyFileS[255] = "pe193.py"
 string resultFileS[255] = "pe193result.txt"
 string pyCmdS[255] = ""

 // --- Erase old Python script file ---
 PushLocation()
 IF EditFile( pyFileS )
  AbandonFile()
 ENDIF
 EraseDiskFile( pyFileS )
 PopLocation()

 // --- Erase old result file ---
 PushLocation()
 IF EditFile( resultFileS )
  AbandonFile()
 ENDIF
 EraseDiskFile( resultFileS )
 PopLocation()

 // --- Build Python script ---
 bufPyI = CreateTempBuffer()
 GotoBufferId( bufPyI )
 BegFile()

 AddLine( "# pe193.py -- generated by TSE SAL" )
 AddLine( "# Project Euler 193 - Squarefree Numbers" )
 AddLine( "import math" )
 AddLine( "import numpy as np" )
 AddLine( "N = 1 << 50" )
 AddLine( "ROOT = math.isqrt(N)" )
 AddLine( "PLIM = math.isqrt(ROOT)" )
 AddLine( "sieve = np.ones(PLIM + 1, dtype=np.bool_)" )
 AddLine( "sieve[:2] = False" )
 AddLine( "for p in range(2, math.isqrt(PLIM) + 1):" )
 AddLine( "    if sieve[p]:" )
 AddLine( "        sieve[p * p : PLIM + 1 : p] = False" )
 AddLine( "primes = np.nonzero(sieve)[0].astype(np.int64)" )
 AddLine( "CHUNK = 1000000" )
 AddLine( "total = 0" )
 AddLine( "for low in range(1, ROOT + 1, CHUNK):" )
 AddLine( "    high = min(ROOT, low + CHUNK - 1)" )
 AddLine( "    nums = np.arange(low, high + 1, dtype=np.int64)" )
 AddLine( "    mu = np.ones(nums.size, dtype=np.int8)" )
 AddLine( "    prod = np.ones(nums.size, dtype=np.int64)" )
 AddLine( "    for p in primes:" )
 AddLine( "        p = int(p)" )
 AddLine( "        pp = p * p" )
 AddLine( "        if pp > high:" )
 AddLine( "            break" )
 AddLine( "        start = ((low + p - 1) // p) * p" )
 AddLine( "        idx = np.arange(start, high + 1, p, dtype=np.int64) - low" )
 AddLine( "        mu[idx] = -mu[idx]" )
 AddLine( "        prod[idx] *= p" )
 AddLine( "        start2 = ((low + pp - 1) // pp) * pp" )
 AddLine( "        if start2 <= high:" )
 AddLine( "            idx2 = np.arange(start2, high + 1, pp, dtype=np.int64) - low" )
 AddLine( "            mu[idx2] = 0" )
 AddLine( "    mask = (mu != 0) & (prod != nums)" )
 AddLine( "    mu[mask] = -mu[mask]" )
 AddLine( "    total += int(np.sum(mu.astype(np.int64) * (N // (nums * nums))))" )
 AddLine( "with open('pe193result.txt', 'w') as f:" )
 AddLine( "    f.write(str(total))" )

 SaveAs( pyFileS, _OVERWRITE_ )
 AbandonFile( bufPyI )

 // --- Run Python ---
 pyCmdS = pyExeS + " " + pyFileS
 DOS( pyCmdS, _DONT_PROMPT_ )

 // --- Read result file ---
 bufResultI = CreateTempBuffer()
 GotoBufferId( bufResultI )
 InsertFile( resultFileS )
 BegFile()
 answerS = GetText( 1, CurrLineLen() )
 AbandonFile( bufResultI )

 // --- Final output ---
 CopyToWinClip( answerS )
 Warn( answerS )
 CopyToWinClip( answerS )
END
