/*
  <version>1.0.0.0.0</version>
  Project Euler Problem 140
  Modified Fibonacci Golden Nuggets

  Generated by: ChatGPT GPT-5.4 Thinking

  Approach:
  - The golden nuggets are:
      2, 5, 21, 42, 152, 296,
      1050, 2037, 7205, 13970, 49392, 95760, ...
  - When grouped in 6 interleaved subsequences, each subsequence satisfies:
      next = 322 * current - previous + 448
  - To avoid 32-bit overflow in TSE SAL, all arithmetic is done with
    non-negative decimal strings.
  - We generate the first 30 nuggets and sum them as decimal strings.

  Final expected answer:
  5673835352990
*/

FORWARD STRING PROC ProcTrimLeadingZeros( STRING inputS )
FORWARD INTEGER PROC ProcCompareBigIntegerStrings( STRING leftS, STRING rightS )
FORWARD STRING PROC ProcAddBigIntegerStrings( STRING leftS, STRING rightS )
FORWARD STRING PROC ProcSubtractBigIntegerStrings( STRING leftS, STRING rightS )
FORWARD STRING PROC ProcMultiplyBigIntegerBySmallInteger( STRING valueS, INTEGER multiplierI )
FORWARD STRING PROC ProcAddSmallIntegerToBigInteger( STRING valueS, INTEGER addendI )
FORWARD STRING PROC ProcMakeNextNugget( STRING previousS, STRING currentS )
FORWARD STRING PROC ProcGetNthNugget( INTEGER targetIndexI )

STRING PROC ProcTrimLeadingZeros( STRING inputS )
  STRING workS[255] = ""
  INTEGER indexI = 1
  INTEGER inputLengthI = 0
  //
  workS = inputS
  inputLengthI = Length( workS )
  WHILE indexI < inputLengthI AND SubStr( workS, indexI, 1 ) == "0"
    indexI = indexI + 1
  ENDWHILE
  Return( SubStr( workS, indexI, inputLengthI - indexI + 1 ) )
END

INTEGER PROC ProcCompareBigIntegerStrings( STRING leftS, STRING rightS )
  STRING normalizedLeftS[255] = ""
  STRING normalizedRightS[255] = ""
  INTEGER leftLengthI = 0
  INTEGER rightLengthI = 0
  INTEGER indexI = 0
  //
  normalizedLeftS  = ProcTrimLeadingZeros( leftS )
  normalizedRightS = ProcTrimLeadingZeros( rightS )
  leftLengthI  = Length( normalizedLeftS )
  rightLengthI = Length( normalizedRightS )
  IF leftLengthI > rightLengthI
    Return( 1 )
  ENDIF
  IF leftLengthI < rightLengthI
    Return( -1 )
  ENDIF
  FOR indexI = 1 TO leftLengthI
    IF SubStr( normalizedLeftS, indexI, 1 ) > SubStr( normalizedRightS, indexI, 1 )
      Return( 1 )
    ENDIF
    IF SubStr( normalizedLeftS, indexI, 1 ) < SubStr( normalizedRightS, indexI, 1 )
      Return( -1 )
    ENDIF
  ENDFOR
  Return( 0 )
END

STRING PROC ProcAddBigIntegerStrings( STRING leftS, STRING rightS )
  STRING normalizedLeftS[255] = ""
  STRING normalizedRightS[255] = ""
  STRING resultS[255] = ""
  INTEGER leftIndexI = 0
  INTEGER rightIndexI = 0
  INTEGER carryI = 0
  INTEGER digitLeftI = 0
  INTEGER digitRightI = 0
  INTEGER digitSumI = 0
  //
  normalizedLeftS  = ProcTrimLeadingZeros( leftS )
  normalizedRightS = ProcTrimLeadingZeros( rightS )
  leftIndexI  = Length( normalizedLeftS )
  rightIndexI = Length( normalizedRightS )
  WHILE leftIndexI > 0 OR rightIndexI > 0 OR carryI > 0
    digitLeftI = 0
    digitRightI = 0
    IF leftIndexI > 0
      digitLeftI = Val( SubStr( normalizedLeftS, leftIndexI, 1 ) )
      leftIndexI = leftIndexI - 1
    ENDIF
    IF rightIndexI > 0
      digitRightI = Val( SubStr( normalizedRightS, rightIndexI, 1 ) )
      rightIndexI = rightIndexI - 1
    ENDIF
    digitSumI = digitLeftI + digitRightI + carryI
    resultS = Chr( digitSumI mod 10 + 48 ) + resultS
    carryI = digitSumI / 10
  ENDWHILE
  Return( ProcTrimLeadingZeros( resultS ) )
END

STRING PROC ProcSubtractBigIntegerStrings( STRING leftS, STRING rightS )
  STRING normalizedLeftS[255] = ""
  STRING normalizedRightS[255] = ""
  STRING resultS[255] = ""
  INTEGER leftIndexI = 0
  INTEGER rightIndexI = 0
  INTEGER borrowI = 0
  INTEGER digitLeftI = 0
  INTEGER digitRightI = 0
  INTEGER digitDiffI = 0
  //
  normalizedLeftS  = ProcTrimLeadingZeros( leftS )
  normalizedRightS = ProcTrimLeadingZeros( rightS )
  leftIndexI  = Length( normalizedLeftS )
  rightIndexI = Length( normalizedRightS )
  WHILE leftIndexI > 0
    digitLeftI = Val( SubStr( normalizedLeftS, leftIndexI, 1 ) ) - borrowI
    digitRightI = 0
    IF rightIndexI > 0
      digitRightI = Val( SubStr( normalizedRightS, rightIndexI, 1 ) )
      rightIndexI = rightIndexI - 1
    ENDIF
    IF digitLeftI < digitRightI
      digitLeftI = digitLeftI + 10
      borrowI = 1
    ELSE
      borrowI = 0
    ENDIF
    digitDiffI = digitLeftI - digitRightI
    resultS = Chr( digitDiffI + 48 ) + resultS
    leftIndexI = leftIndexI - 1
  ENDWHILE
  Return( ProcTrimLeadingZeros( resultS ) )
END

STRING PROC ProcMultiplyBigIntegerBySmallInteger( STRING valueS, INTEGER multiplierI )
  STRING normalizedValueS[255] = ""
  STRING resultS[255] = ""
  INTEGER valueIndexI = 0
  INTEGER carryI = 0
  INTEGER digitValueI = 0
  INTEGER productI = 0
  //
  normalizedValueS = ProcTrimLeadingZeros( valueS )
  IF normalizedValueS == "0" OR multiplierI == 0
    Return( "0" )
  ENDIF
  valueIndexI = Length( normalizedValueS )
  WHILE valueIndexI > 0 OR carryI > 0
    digitValueI = 0
    IF valueIndexI > 0
      digitValueI = Val( SubStr( normalizedValueS, valueIndexI, 1 ) )
      valueIndexI = valueIndexI - 1
    ENDIF
    productI = digitValueI * multiplierI + carryI
    resultS = Chr( productI mod 10 + 48 ) + resultS
    carryI = productI / 10
  ENDWHILE
  Return( ProcTrimLeadingZeros( resultS ) )
END

STRING PROC ProcAddSmallIntegerToBigInteger( STRING valueS, INTEGER addendI )
  STRING addendS[32] = ""
  //
  addendS = Str( addendI )
  Return( ProcAddBigIntegerStrings( valueS, addendS ) )
END

STRING PROC ProcMakeNextNugget( STRING previousS, STRING currentS )
  STRING multipliedS[255] = ""
  STRING differenceS[255] = ""
  STRING nextS[255] = ""
  //
  multipliedS = ProcMultiplyBigIntegerBySmallInteger( currentS, 322 )
  differenceS = ProcSubtractBigIntegerStrings( multipliedS, previousS )
  nextS = ProcAddSmallIntegerToBigInteger( differenceS, 448 )
  Return( nextS )
END

STRING PROC ProcGetNthNugget( INTEGER targetIndexI )
  STRING seed1PrevS[255] = "2"
  STRING seed1CurrS[255] = "1050"
  STRING seed2PrevS[255] = "5"
  STRING seed2CurrS[255] = "2037"
  STRING seed3PrevS[255] = "21"
  STRING seed3CurrS[255] = "7205"
  STRING seed4PrevS[255] = "42"
  STRING seed4CurrS[255] = "13970"
  STRING seed5PrevS[255] = "152"
  STRING seed5CurrS[255] = "49392"
  STRING seed6PrevS[255] = "296"
  STRING seed6CurrS[255] = "95760"
  STRING nextS[255] = ""
  INTEGER cycleCountI = 0
  INTEGER remainderI = 0
  //
  CASE targetIndexI
    WHEN 1
      Return( "2" )
    WHEN 2
      Return( "5" )
    WHEN 3
      Return( "21" )
    WHEN 4
      Return( "42" )
    WHEN 5
      Return( "152" )
    WHEN 6
      Return( "296" )
    WHEN 7
      Return( "1050" )
    WHEN 8
      Return( "2037" )
    WHEN 9
      Return( "7205" )
    WHEN 10
      Return( "13970" )
    WHEN 11
      Return( "49392" )
    WHEN 12
      Return( "95760" )
  ENDCASE
  cycleCountI = ( targetIndexI - 1 ) / 6
  remainderI = ( targetIndexI - 1 ) mod 6
  WHILE cycleCountI > 1
    nextS = ProcMakeNextNugget( seed1PrevS, seed1CurrS )
    seed1PrevS = seed1CurrS
    seed1CurrS = nextS
    //
    nextS = ProcMakeNextNugget( seed2PrevS, seed2CurrS )
    seed2PrevS = seed2CurrS
    seed2CurrS = nextS
    //
    nextS = ProcMakeNextNugget( seed3PrevS, seed3CurrS )
    seed3PrevS = seed3CurrS
    seed3CurrS = nextS
    //
    nextS = ProcMakeNextNugget( seed4PrevS, seed4CurrS )
    seed4PrevS = seed4CurrS
    seed4CurrS = nextS
    //
    nextS = ProcMakeNextNugget( seed5PrevS, seed5CurrS )
    seed5PrevS = seed5CurrS
    seed5CurrS = nextS
    //
    nextS = ProcMakeNextNugget( seed6PrevS, seed6CurrS )
    seed6PrevS = seed6CurrS
    seed6CurrS = nextS
    //
    cycleCountI = cycleCountI - 1
  ENDWHILE
  CASE remainderI
    WHEN 0
      Return( seed1CurrS )
    WHEN 1
      Return( seed2CurrS )
    WHEN 2
      Return( seed3CurrS )
    WHEN 3
      Return( seed4CurrS )
    WHEN 4
      Return( seed5CurrS )
    OTHERWISE
      Return( seed6CurrS )
  ENDCASE
END

PROC Main()
  STRING sumS[255] = "0"
  STRING nuggetS[255] = ""
  STRING resultS[255] = ""
  INTEGER indexI = 0
  //
  FOR indexI = 1 TO 30
    nuggetS = ProcGetNthNugget( indexI )
    sumS = ProcAddBigIntegerStrings( sumS, nuggetS )
  ENDFOR
  resultS = sumS
  CopyToWinClip( resultS )
  Warn( resultS )
END
