/*
 Euler Project 221 - Alexandrian Integers
 version 1.0.0.0.4
 creator LLM: ChatGPT GPT-5.4 Thinking
 history:
 - 1.0.0.0.4 create and run Python from within TSE SAL
 - created by ChatGPT GPT-5.4 Thinking
*/
PROC Main()
    INTEGER bufPyI = 0
    INTEGER bufResultI = 0
    STRING answerS[255] = ""
    STRING pyExeS[255] = "g:\language\computer\python\python\python.exe"
    STRING pyFileS[255] = "pe221.py"
    STRING resultFileS[255] = "pe221result.txt"
    STRING pyCmdS[255] = ""
    STRING indent1S[8] = "    "
    STRING indent2S[16] = "        "
    STRING indent3S[24] = "            "
    STRING indent4S[32] = "                "
    STRING indent5S[40] = "                    "
    //
    PushLocation()
    IF EditFile( pyFileS )
        AbandonFile()
    ENDIF
    EraseDiskFile( pyFileS )
    PopLocation()
    //
    PushLocation()
    IF EditFile( resultFileS )
        AbandonFile()
    ENDIF
    EraseDiskFile( resultFileS )
    PopLocation()
    //
    bufPyI = CreateTempBuffer()
    GotoBufferId( bufPyI )
    BegFile()
    //
    AddLine( "# pe221.py -- generated by pe221.s (TSE SAL)" )                                    // 1
    AddLine( "# Project Euler 221 - Alexandrian Integers" )                                      // 2
    AddLine( "from math import isqrt" )                                                          // 3
    AddLine( "TARGET = 150000" )                                                                 // 4
    AddLine( "P_LIMIT = 80000" )                                                                 // 5
    AddLine( "" )                                                                                // 6
    AddLine( "def prime_list(limit):" )                                                          // 7
    AddLine( "sieve = bytearray(b'\x01') * (limit + 1)" )                                        // 8
    AddLine( "if limit >= 0:" )                                                                  // 9
    AddLine( "sieve[0] = 0" )                                                                    // 10
    AddLine( "if limit >= 1:" )                                                                  // 11
    AddLine( "sieve[1] = 0" )                                                                    // 12
    AddLine( "top = isqrt(limit)" )                                                              // 13
    AddLine( "for prime in range(2, top + 1):" )                                                 // 14
    AddLine( "if sieve[prime]:" )                                                                // 15
    AddLine( "start = prime * prime" )                                                           // 16
    AddLine( "step = prime" )                                                                    // 17
    AddLine( "count = ((limit - start) // step) + 1" )                                           // 18
    AddLine( "sieve[start : limit + 1 : step] = b'\x00' * count" )                               // 19
    AddLine( "return [i for i in range(2, limit + 1) if sieve[i]]" )                             // 20
    AddLine( "" )                                                                                // 21
    AddLine( "def factorize(number, primes):" )                                                  // 22
    AddLine( "factors = []" )                                                                    // 23
    AddLine( "rest = number" )                                                                   // 24
    AddLine( "for prime in primes:" )                                                            // 25
    AddLine( "if prime * prime > rest:" )                                                        // 26
    AddLine( "break" )                                                                           // 27
    AddLine( "if rest % prime == 0:" )                                                           // 28
    AddLine( "power = 0" )                                                                       // 29
    AddLine( "while rest % prime == 0:" )                                                        // 30
    AddLine( "rest //= prime" )                                                                  // 31
    AddLine( "power += 1" )                                                                      // 32
    AddLine( "factors.append((prime, power))" )                                                  // 33
    AddLine( "if rest > 1:" )                                                                    // 34
    AddLine( "factors.append((rest, 1))" )                                                       // 35
    AddLine( "return factors" )                                                                  // 36
    AddLine( "" )                                                                                // 37
    AddLine( "def small_divisors(number, factors):" )                                            // 38
    AddLine( "divisors = [1]" )                                                                  // 39
    AddLine( "for prime, power in factors:" )                                                    // 40
    AddLine( "new_divisors = []" )                                                               // 41
    AddLine( "multiplier = 1" )                                                                  // 42
    AddLine( "for _ in range(power + 1):" )                                                      // 43
    AddLine( "for divisor in divisors:" )                                                        // 44
    AddLine( "value = divisor * multiplier" )                                                    // 45
    AddLine( "if value <= number // value:" )                                                    // 46
    AddLine( "new_divisors.append(value)" )                                                      // 47
    AddLine( "multiplier *= prime" )                                                             // 48
    AddLine( "divisors = new_divisors" )                                                         // 49
    AddLine( "return divisors" )                                                                 // 50
    AddLine( "" )                                                                                // 51
    AddLine( "primes = prime_list(isqrt(P_LIMIT * P_LIMIT + 1) + 10)" )                          // 52
    AddLine( "values = set()" )                                                                  // 53
    AddLine( "for p in range(1, P_LIMIT + 1):" )                                                 // 54
    AddLine( "n = p * p + 1" )                                                                   // 55
    AddLine( "factors = factorize(n, primes)" )                                                  // 56
    AddLine( "for divisor in small_divisors(n, factors):" )                                      // 57
    AddLine( "value = p * (p + divisor) * (p + n // divisor)" )                                  // 58
    AddLine( "values.add(value)" )                                                               // 59
    AddLine( "ordered = sorted(values)" )                                                        // 60
    AddLine( "if len(ordered) < TARGET:" )                                                       // 61
    AddLine( "answer = 'Search limit too small'" )                                               // 62
    AddLine( "else:" )                                                                           // 63
    AddLine( "answer = str(ordered[TARGET - 1])" )                                               // 64
    AddLine( "handle = open('pe221result.txt', 'w')" )                                           // 65
    AddLine( "handle.write(answer)" )                                                            // 66
    AddLine( "handle.close()" )                                                                  // 67
    //
    GotoBufferId( bufPyI )
    //
    GotoLine(8)   BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(9)   BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(10)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(11)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(12)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(13)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(14)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(15)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(16)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(17)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(18)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(19)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(20)  BegLine()  InsertText( indent1S, _INSERT_ )
    //
    GotoLine(23)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(24)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(25)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(26)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(27)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(28)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(29)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(30)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(31)  BegLine()  InsertText( indent4S, _INSERT_ )
    GotoLine(32)  BegLine()  InsertText( indent4S, _INSERT_ )
    GotoLine(33)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(34)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(35)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(36)  BegLine()  InsertText( indent1S, _INSERT_ )
    //
    GotoLine(39)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(40)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(41)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(42)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(43)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(44)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(45)  BegLine()  InsertText( indent4S, _INSERT_ )
    GotoLine(46)  BegLine()  InsertText( indent4S, _INSERT_ )
    GotoLine(47)  BegLine()  InsertText( indent5S, _INSERT_ )
    GotoLine(48)  BegLine()  InsertText( indent3S, _INSERT_ )
    GotoLine(49)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(50)  BegLine()  InsertText( indent1S, _INSERT_ )
    //
    GotoLine(55)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(56)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(57)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(58)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(59)  BegLine()  InsertText( indent2S, _INSERT_ )
    GotoLine(62)  BegLine()  InsertText( indent1S, _INSERT_ )
    GotoLine(64)  BegLine()  InsertText( indent1S, _INSERT_ )
    //
    SaveAs( pyFileS, _OVERWRITE_ )
    AbandonFile()
    //
    pyCmdS = pyExeS + " " + pyFileS
    Dos( pyCmdS, _DONT_PROMPT_ )
    //
    bufResultI = CreateTempBuffer()
    GotoBufferId( bufResultI )
    InsertFile( resultFileS )
    BegFile()
    answerS = GetText( 1, CurrLineLen() )
    AbandonFile()
    //
    CopyToWinClip( answerS )
    Warn( answerS )
    CopyToWinClip( answerS )
    //
    Return()
END
