// ============================================================
// File: eulerproject0258.s
// Purpose: Create and run a Python program for Project Euler 258
//          "A Lagged Fibonacci Sequence"
//
// <version>15</version>
// LLM: ChatGPT GPT-5.4 Thinking
//
// History:
//   15 - ChatGPT - Creates pe258.py from TSE SAL, runs it,
//                  reads pe258result.txt, shows/copies result.
// ============================================================

proc Main()
    integer bufferPyI        = 0
    integer bufferResultI    = 0
    string answerS[255]      = ""
    string pythonExeS[255]   = "g:\language\computer\python\python\python.exe"
    string pythonFileS[255]  = "pe258.py"
    string resultFileS[255]  = "pe258result.txt"
    string commandS[255]     = ""
    string quoteS[2]         = ""
    //
    quoteS = Chr( 34 )
    //
    PushLocation()
    PushBlock()
    if EditFile( pythonFileS )
        AbandonFile()
    endif
    EraseDiskFile( pythonFileS )
    PopBlock()
    PopLocation()
    //
    PushLocation()
    PushBlock()
    if EditFile( resultFileS )
        AbandonFile()
    endif
    EraseDiskFile( resultFileS )
    PopBlock()
    PopLocation()
    //
    bufferPyI = CreateTempBuffer()
    GotoBufferId( bufferPyI )
    BegFile()
    //
    AddLine( "# pe258.py -- generated by eulerproject0258.s (TSE SAL)" )
    AddLine( "# Project Euler 258 - A Lagged Fibonacci Sequence" )
    AddLine( "MOD = 20092010" )
    AddLine( "D = 2000" )
    AddLine( "" )
    AddLine( "def mul_poly_mod(a, b):" )
    AddLine( "    c = [0] * (2 * D - 1)" )
    AddLine( "    for i, ai in enumerate(a):" )
    AddLine( "        if ai:" )
    AddLine( "            for j, bj in enumerate(b):" )
    AddLine( "                if bj:" )
    AddLine( "                    c[i + j] += ai * bj" )
    AddLine( "    for i in range(2 * D - 2, D - 1, -1):" )
    AddLine( "        t = c[i] % MOD" )
    AddLine( "        if t:" )
    AddLine( "            c[i - D] = (c[i - D] + t) % MOD" )
    AddLine( "            c[i - D + 1] = (c[i - D + 1] + t) % MOD" )
    AddLine( "    return [x % MOD for x in c[:D]]" )
    AddLine( "" )
    AddLine( "def x_pow_mod(n):" )
    AddLine( "    if n < 0:" )
    AddLine( "        raise ValueError('n must be non-negative')" )
    AddLine( "    res = [0] * D" )
    AddLine( "    res[0] = 1" )
    AddLine( "    base = [0] * D" )
    AddLine( "    base[1] = 1" )
    AddLine( "    e = n" )
    AddLine( "    while e:" )
    AddLine( "        if e & 1:" )
    AddLine( "            res = mul_poly_mod(res, base)" )
    AddLine( "        e >>= 1" )
    AddLine( "        if e:" )
    AddLine( "            base = mul_poly_mod(base, base)" )
    AddLine( "    return res" )
    AddLine( "" )
    AddLine( "def g_mod(n):" )
    AddLine( "    if 0 <= n <= D - 1:" )
    AddLine( "        return 1" )
    AddLine( "    coeffs = x_pow_mod(n)" )
    AddLine( "    return sum(coeffs) % MOD" )
    AddLine( "" )
    AddLine( "def self_test():" )
    AddLine( "    assert g_mod(0) == 1" )
    AddLine( "    assert g_mod(1999) == 1" )
    AddLine( "    assert g_mod(2000) == 2" )
    AddLine( "    assert g_mod(2001) == 2" )
    AddLine( "    assert g_mod(3999) == 3" )
    AddLine( "    limit = 6000" )
    AddLine( "    g = [1] * D" )
    AddLine( "    for k in range(D, limit + 1):" )
    AddLine( "        g.append((g[k - D] + g[k - D + 1]) % MOD)" )
    AddLine( "    for k in (0, 1, 2, 1999, 2000, 2001, 2500, 3999, 4000, 5432, 6000):" )
    AddLine( "        assert g_mod(k) == g[k]" )
    AddLine( "" )
    AddLine( "def main():" )
    AddLine( "    self_test()" )
    AddLine( "    answer = str(g_mod(10 ** 18))" )
    AddLine( "    open('pe258result.txt', 'w').write(answer)" )
    AddLine( "" )
    AddLine( "if __name__ == '__main__':" )
    AddLine( "    main()" )
    //
    SaveAs( pythonFileS, _OVERWRITE_ )
    AbandonFile( bufferPyI )
    //
    commandS = quoteS + pythonExeS + quoteS + " " + quoteS + pythonFileS + quoteS
    Dos( commandS, _DONT_PROMPT_ )
    //
    bufferResultI = CreateTempBuffer()
    GotoBufferId( bufferResultI )
    InsertFile( resultFileS )
    BegFile()
    answerS = GetText( 1, CurrLineLen() )
    AbandonFile( bufferResultI )
    //
    CopyToWinClip( answerS )
    Warn( answerS )
    CopyToWinClip( answerS )
end
