// File: Euler207.s
// Version: 2.0
// Created by: Google Gemini
// Problem: Project Euler 207 - Integer partitions

// Helper function to safely zero-pad numbers
// Ensures compatibility without relying on advanced Format() features
string proc Pad4(integer num)
    string s[4] = Str(num)
    while (Length(s) < 4)
        s = "0" + s
    endwhile
    Return(s)
end

// Function to multiply two integers and return an exact string
// Avoids 32-bit signed integer limits for numbers exceeding 2.14 billion
string proc BigMult(integer n1, integer n2)
    integer a = n1 / 10000
    integer b = n1 MOD 10000
    integer c = n2 / 10000
    integer d = n2 MOD 10000

    // n1 * n2 = (a*10000 + b) * (c*10000 + d)
    // = (a*c)*10^8 + (a*d + b*c)*10^4 + (b*d)

    integer p1 = b * d
    integer p2 = a * d + b * c + (p1 / 10000)
    integer p3 = a * c + (p2 / 10000)

    integer r1 = p1 MOD 10000
    integer r2 = p2 MOD 10000
    integer r3 = p3

    string s1[4] = Pad4(r1)
    string s2[4] = Pad4(r2)
    string s3[20] = Str(r3)

    string res[30] = s3 + s2 + s1

    // Trim leading zeros mathematically generated by the string
    while (Length(res) > 1 AND SubStr(res, 1, 1) == "0")
        res = SubStr(res, 2, Length(res) - 1)
    endwhile

    Return(res)
end

proc main()
    integer total_n = 1
    integer perfect_count = 1
    integer next_perfect_threshold = 3 // n = 2^2 - 1
    integer power_of_2 = 4             // next power of 2
    integer limit = 12345
    string final_answer[64] = ""

    // Loop until perfect_count / total_n < 1 / 12345
    // Avoid floats via cross-multiplication: total_n > perfect_count * limit
    while (1)
        total_n = total_n + 1

        // Track the perfect partitions dynamically
        if (total_n == next_perfect_threshold)
            perfect_count = perfect_count + 1
            power_of_2 = power_of_2 * 2
            next_perfect_threshold = power_of_2 - 1
        endif

        // Condition check to break the loop exactly at the smallest ratio
        if (total_n > (perfect_count * limit))
            // Problem requests m, where m = n * (n + 1)
            final_answer = BigMult(total_n, total_n + 1)
            break
        endif
    endwhile

    CopyToWinClip(final_answer)
    Warn(final_answer)
    CopyToWinClip(final_answer)

    if (GetBufferId("EulerOutput") == 0)
        CreateBuffer("EulerOutput")
    endif
    AddLine("Project Euler 207 Result (m):")
    AddLine(final_answer)
end
