; MENUCOLR configuration file
; Version: 1.0.0.0.2
; Updated: 2026-09-22 13:02:00 CEST
;
; false = show the informative Warn() box when MENUCOLR starts
; true  = do not show the informative Warn() box
silent=false
