; MAKECSV1 configuration file
; Package version: 1.0.0.0.1
; Created: 2026-09-21 08:12:46 UTC
;
; The original MAKECSV.S version 1.1 does not read an INI file.
; These values are placeholders for a possible future version.

[makecsv1]
definesuffix=
convertquotes=ask
