@echo off

rem ************************************************************************
rem *                                                                      *
rem *   TFSFile.BAT                                                        *
rem *                                                                      *
rem *   Start file manager in batch mode                                   *
rem *                                                                      *
rem *   Version         V3.10/28.04.95                                     *
rem *   Copyright       (c) 1994,95 by DiK                                 *
rem *                                                                      *
rem *   History                                                            *
rem *                                                                      *
rem *   V3.10/28.04.95  extended version (file compare)                    *
rem *                                                                      *
rem ************************************************************************

e -etsefileb

