; SEARCHCOMPILE configuration
; Version: 1.0.0.0.6
; Date: 2026-09-21
; Time: 19:03:11 CEST
;
; Change these initial proposals as required.

[SearchCompile]
compile_dat=
search_string=Borland
search_options=ix
file_extension=.c
