; PGFX25 initialization/reference file
; Package version: 1.0.0.0.0
; Date and time: 2026-09-18 15:11:16 UTC
;
; PGFX25 PgfRev1054 does not currently parse this file.
; These entries document the built-in initial values.

[PGFX25]
autosave=yes
foldbuffer=pgffold.dat
