 @REM version: 1.0.0.0.0 [kn, ri, sa, 05-09-2026 00:37:52]

 @echo off
 g:
 cd /d g:\versioncontrol\git\ddd01\DLG222\
 git add deldlg.bat
 git add dialog.doc
 git add dialog.s
 git add dialog.si
 git add dialogp.s
 git add dlg222.zip
 git add dlg222_readme.md
 git add dlg25.ui
 git add dlg30.ui
 git add dlg42.ui
 git add dlgascii.dlg
 git add dlgascii.s
 git add dlgascii.si
 git add dlgbuff.dlg
 git add dlgbuff.s
 git add dlgbuff.si
 git add dlgcomp.dlg
 git add dlgcomp.s
 git add dlgcomp.si
 git add dlgcompx.s
 git add dlgfind.dlg
 git add dlgfind.s
 git add dlgfind.si
 git add dlgfnddo.dlg
 git add dlgfnddo.s
 git add dlgfnddo.si
 git add dlggoto.dlg
 git add dlggoto.s
 git add dlggoto.si
 git add dlghist.s
 git add dlghist1.dlg
 git add dlghist1.si
 git add dlghist2.dlg
 git add dlghist2.si
 git add dlghist3.dlg
 git add dlghist3.si
 git add dlgmcc.dlg
 git add dlgmcc.s
 git add dlgmcc.si
 git add dlgop16a.dlg
 git add dlgop16a.si
 git add dlgop16d.s
 git add dlgop32a.dlg
 git add dlgop32a.si
 git add dlgop32b.dlg
 git add dlgop32b.si
 git add dlgopen.s
 git add dlgrcnt.dlg
 git add dlgrcnt.s
 git add dlgrcnt.si
 git add dlgrplc.dlg
 git add dlgrplc.s
 git add dlgrplc.si
 git add dlgsetu1.dlg
 git add dlgsetu1.si
 git add dlgsetu2.dlg
 git add dlgsetu2.si
 git add dlgsetup.s
 git add dlgvideo.dlg
 git add dlgvideo.s
 git add dlgvideo.si
 git add drivelst.s
 git add file_id.diz
 git add getfldr.dll
 git add getfldr.dpr
 git add inpbox.s
 git add instdlg.bat
 git add listfile.asm
 git add listfile.bin
 git add msgbox.s
 git add msgbox.si
 git add scgtfldr.si
 git add schelp.si
 git add scop16w.si
 git add scop32w.si
 git add scoptyp1.si
 git add scoptyp2.si
 git add scpaint.si
 git add scrun.si
 git add sctoken.si
 git add scver.si
 git add scwinclp.si
 git add setvideo.s
 git add tsecomp.bat
 git commit -m "Update dlg222 directory files"
 git push origin HEAD:TRUNK
 start https://github.com/knudvaneeden/tse/tree/TRUNK/DLG222
