@echo off
rem ISDIR DLL build script
rem Version 1.0.0.0.2 - 2026-09-11
rem Generated by OpenAI Codex (GPT-5)

set "TSEMACRODIR=%~1"

if exist "%~dp0bcc32.exe" goto compiler_bin
set "BCCROOT=C:\Borland\BCC55"
goto compiler_ready

:compiler_bin
set "BCCROOT=%~dp0.."

:compiler_ready
set "PATH=%BCCROOT%\Bin;%PATH%"

bcc32 -c -O2 -w- -tWD -I"%BCCROOT%\Include" isdir.c
if errorlevel 1 goto failed

ilink32 -Tpd -aa -x -L"%BCCROOT%\Lib" c0d32.obj isdir.obj,isdir.dll,,import32.lib cw32.lib,isdir.def
if errorlevel 1 goto failed

echo Built isdir.dll successfully.

if "%TSEMACRODIR%" == "" goto compile_sal_here
if not exist "%TSEMACRODIR%\isdir.s" goto bad_macro_directory
copy /y "isdir.dll" "%TSEMACRODIR%\isdir.dll" >nul
if errorlevel 1 goto copy_failed
pushd "%TSEMACRODIR%"
sc32 isdir.s
set "SALERROR=%ERRORLEVEL%"
popd
if not "%SALERROR%" == "0" goto sal_failed
echo Copied isdir.dll and compiled isdir.s in "%TSEMACRODIR%".
goto end

:compile_sal_here
if not exist "%~dp0isdir.s" goto end
sc32 isdir.s
if errorlevel 1 goto sal_failed
echo Built isdir.mac successfully.
goto end

:bad_macro_directory
echo DLL built, but isdir.s was not found in "%TSEMACRODIR%".
goto end

:copy_failed
echo DLL built, but copying it to "%TSEMACRODIR%" failed.
goto end

:sal_failed
echo isdir.dll was built, but the SAL compilation failed.
goto end

:failed
echo Build failed.

:end
