/*
 * isdir.c - Win32 replacement for the original TSE ISDIR.BIN routine
 * Version 1.0.0.0.2 - 2026-09-11
 * Generated by OpenAI Codex (GPT-5)
 *
 * Compatible with Borland C++ 5.5.1 and 32-bit TSE Pro.
 */

#include <windows.h>

/* Borland C++ 5.5.1's Windows headers do not define this newer name. */
#ifndef INVALID_FILE_ATTRIBUTES
#define INVALID_FILE_ATTRIBUTES ((DWORD)-1)
#endif

typedef struct SalStringTag {
    short size;
    char data[256];
} SalString;

int WINAPI IsDir(const SalString *dirName)
{
    char path[260];
    DWORD attributes;
    int length;
    int index;

    if (dirName == NULL)
        return 0;

    length = (int)dirName->size;
    if (length <= 0 || length >= (int)sizeof(path))
        return 0;

    for (index = 0; index < length; ++index)
        path[index] = dirName->data[index];
    path[length] = '\0';

    attributes = GetFileAttributesA(path);
    if (attributes == INVALID_FILE_ATTRIBUTES)
        return 0;

    return (attributes & FILE_ATTRIBUTE_DIRECTORY) != 0 ? 1 : 0;
}

BOOL WINAPI DllMain(HINSTANCE instance, DWORD reason, LPVOID reserved)
{
    (void)instance;
    (void)reason;
    (void)reserved;
    return TRUE;
}
