/*
  isdir.s - TSE SAL demonstration for isdir.dll
  Version 1.0.0.0.2 - 2026-09-11
  Generated by OpenAI Codex (GPT-5)
*/

#include ["isdir.inc"]

proc Main()
    string dirNameS[255] = ""
    integer isDirectoryB = FALSE

    if Ask("Directory name:", dirNameS, _EDIT_HISTORY_)
        isDirectoryB = IsDir(dirNameS)
        if isDirectoryB
            Warn("Directory exists: ", dirNameS)
        else
            Warn("Not an existing directory: ", dirNameS)
        endif
    endif
end
