/*
 * bitsetdll.cpp - TSE WordSet/VarTabs conversion DLL
 * Version 1.0.0.0.5
 * Generated by OpenAI Codex (GPT-5)
 *
 * Borland C++ 5.5 compatible: no C++11 features are used.
 */
#include <windows.h>
#include <ctype.h>
#include <stdio.h>
#include <string.h>

#define BITSET_BYTES 32
#define HEX_CHARS 64

typedef struct SalStringTag {
    short size;
    char data[256];
} SalString;

static int hexValue(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    return -1;
}

static int decodeHex(const SalString *text, unsigned char bits[BITSET_BYTES])
{
    int i, hi, lo;
    if (text == NULL || text->size != HEX_CHARS) return 0;
    for (i = 0; i < BITSET_BYTES; ++i) {
        hi = hexValue(text->data[i * 2]);
        lo = hexValue(text->data[i * 2 + 1]);
        if (hi < 0 || lo < 0) return 0;
        bits[i] = (unsigned char)((hi << 4) | lo);
    }
    return 1;
}

static int encodeHex(const unsigned char bits[BITSET_BYTES], SalString *output,
                     int outputSize)
{
    static const char digits[] = "0123456789ABCDEF";
    int i;
    if (output == NULL || outputSize < HEX_CHARS) return 0;
    for (i = 0; i < BITSET_BYTES; ++i) {
        output->data[i * 2] = digits[bits[i] >> 4];
        output->data[i * 2 + 1] = digits[bits[i] & 15];
    }
    output->size = HEX_CHARS;
    return 1;
}

static void setBit(unsigned char bits[BITSET_BYTES], unsigned int value)
{
    bits[value >> 3] |= (unsigned char)(1U << (value & 7));
}

extern "C" int WINAPI WrdChrs2WrdHex(const SalString *letterSet,
                                      SalString *resultHex, int resultSize)
{
    unsigned char bits[BITSET_BYTES];
    unsigned int i, first, last, value;
    if (letterSet == NULL || letterSet->size < 0 || letterSet->size > 255) return 0;
    memset(bits, 0, sizeof(bits));
    i = 0;
    while (i < (unsigned int)letterSet->size) {
        first = (unsigned char)letterSet->data[i++];
        setBit(bits, first);
        if (i + 1 < (unsigned int)letterSet->size &&
            letterSet->data[i] == '-' &&
            (unsigned char)letterSet->data[i + 1] >= first) {
            ++i;
            last = (unsigned char)letterSet->data[i++];
            for (value = first + 1; value <= last; ++value) setBit(bits, value);
        }
    }
    return encodeHex(bits, resultHex, resultSize);
}

extern "C" int WINAPI WrdHex2WrdChrs(const SalString *wordHex,
                                      SalString *result, int resultSize)
{
    unsigned char bits[BITSET_BYTES];
    int value, start, end, used = 0;
    if (!decodeHex(wordHex, bits) || result == NULL || resultSize < 0) return 0;
    for (value = 0; value < 256;) {
        if ((bits[value >> 3] & (1U << (value & 7))) == 0) { ++value; continue; }
        start = value;
        while (value + 1 < 256 &&
               (bits[(value + 1) >> 3] & (1U << ((value + 1) & 7))) != 0) ++value;
        end = value;
        if (end - start >= 2) {
            if (used + 3 > resultSize) return 0;
            result->data[used++] = (char)start;
            result->data[used++] = '-';
            result->data[used++] = (char)end;
        } else {
            if (used + (end - start + 1) > resultSize) return 0;
            result->data[used++] = (char)start;
            if (end != start) result->data[used++] = (char)end;
        }
        ++value;
    }
    result->size = (short)used;
    return 1;
}

extern "C" int WINAPI TabPosns2TabHex(const SalString *positions,
                                       SalString *resultHex, int resultSize)
{
    unsigned char bits[BITSET_BYTES];
    int index;
    unsigned long value;
    int valid = 1;
    if (positions == NULL || positions->size < 0 || positions->size > 255) return 0;
    memset(bits, 0, sizeof(bits));
    index = 0;
    while (index < positions->size) {
        while (index < positions->size &&
               (positions->data[index] == ' ' || positions->data[index] == '\t')) ++index;
        if (index >= positions->size) break;
        if (!isdigit((unsigned char)positions->data[index])) {
            valid = 0;
            ++index;
            continue;
        }
        value = 0;
        while (index < positions->size &&
               isdigit((unsigned char)positions->data[index])) {
            value = value * 10UL +
                    (unsigned long)(positions->data[index] - '0');
            ++index;
        }
        if (value > 255UL) valid = 0;
        else setBit(bits, (unsigned int)value);
        if (index < positions->size && positions->data[index] != ' ' &&
            positions->data[index] != '\t') valid = 0;
    }
    if (!encodeHex(bits, resultHex, resultSize)) return 0;
    return valid;
}

extern "C" int WINAPI TabHex2TabPosns(const SalString *tabHex,
                                       SalString *result, int resultSize)
{
    unsigned char bits[BITSET_BYTES];
    int value, used = 0, count;
    char number[4];
    if (!decodeHex(tabHex, bits) || result == NULL || resultSize < 0) return 0;
    result->size = 0;
    for (value = 0; value < 256; ++value) {
        if ((bits[value >> 3] & (1U << (value & 7))) == 0) continue;
        sprintf(number, "%d", value);
        count = (int)strlen(number);
        if (used + count + (used != 0 ? 1 : 0) > resultSize) return 0;
        if (used != 0) result->data[used++] = ' ';
        memcpy(result->data + used, number, count);
        used += count;
    }
    result->size = (short)used;
    return 1;
}

BOOL WINAPI DllMain(HINSTANCE instance, DWORD reason, LPVOID reserved)
{
    (void)instance; (void)reason; (void)reserved;
    return TRUE;
}
