/*
  bitsetdll.s - TSE SAL demonstration and wrapper
  Version 1.0.0.0.5
  Generated by OpenAI Codex (GPT-5)

  The DLL boundary uses 64 printable hexadecimal characters.  This avoids
  passing embedded NUL bytes through the Windows DLL string interface.
*/

dll "bitsetdll.dll"
    integer proc WrdChrs2WrdHex(string letterSetS,
                               var string resultHexS)
    integer proc WrdHex2WrdChrs(string wordHexS,
                               var string resultS)
    integer proc TabPosns2TabHex(string positionsS,
                                var string resultHexS)
    integer proc TabHex2TabPosns(string tabHexS,
                                var string resultS)
end

string proc FnNibbleToHex(integer nibbleI)
    string digitsS[16] = "0123456789ABCDEF"
    return(SubStr(digitsS, nibbleI + 1, 1))
end

integer proc FnHexToNibble(string digitS)
    integer positionI = Pos(Upper(digitS), "0123456789ABCDEF")
    return(positionI - 1)
end

string proc FnBitSetToHex(string bitSetS)
    integer indexI = 0
    integer valueI = 0
    string resultS[64] = ""
    for indexI = 1 to 32
        valueI = Asc(SubStr(bitSetS, indexI, 1))
        resultS = resultS + FnNibbleToHex(valueI / 16)
        resultS = resultS + FnNibbleToHex(valueI mod 16)
    endfor
    return(resultS)
end

string proc FnHexToBitSet(string hexS)
    integer indexI = 0
    integer highI = 0
    integer lowI = 0
    string resultS[32] = ""
    if Length(hexS) <> 64
        return("")
    endif
    for indexI = 1 to 64 by 2
        highI = FnHexToNibble(SubStr(hexS, indexI, 1))
        lowI  = FnHexToNibble(SubStr(hexS, indexI + 1, 1))
        if highI < 0 or lowI < 0
            return("")
        endif
        resultS = resultS + Chr(highI * 16 + lowI)
    endfor
    return(resultS)
end

proc Main()
    string wordCharactersS[255] = ""
    string tabPositionsS[255] = ""
    string resultHexS[255] = ""
    string roundTripS[255] = ""

    if not Ask("Enter WordSet characters/ranges:", wordCharactersS)
        return()
    endif
    if not WrdChrs2WrdHex(wordCharactersS, resultHexS)
        Warn("WordSet conversion failed.")
        return()
    endif
    if not WrdHex2WrdChrs(resultHexS, roundTripS)
        Warn("WordSet reverse conversion failed.")
        return()
    endif

    if not Ask("Enter variable tab positions:", tabPositionsS)
        return()
    endif
    if not TabPosns2TabHex(tabPositionsS, resultHexS)
        Warn("The tab list contains invalid input.")
        return()
    endif
    if not TabHex2TabPosns(resultHexS, tabPositionsS)
        Warn("VarTabs reverse conversion failed.")
        return()
    endif

    Warn("WordSet: ", roundTripS, "   VarTabs: ", tabPositionsS)
end
