; MKSAVDIR configuration
; Version: 1.0.0.0.0
; Updated: 2026-09-22 14:20:16 CEST
;
; false = show the informative Warn() box when MKSAVDIR is run
; true  = suppress only that startup Warn() box

[mksavdir]
silent=false
